import { ViewProps } from "../utils/api";

export const data1: ViewProps = {
  id: "M1470",
  originalId: "NBRC_M249",
  name: "(Unnamed medium)",
  srcLabel: "NBRC",
  srcUrl: "https://www.nite.go.jp/nbrc/catalogue/NBRCMediumDetailServlet?NO=249",
  ph: "6.5",
  components: [
    {
      index: 1,
      name: "main solution 1",
      items: [
        {
          id: "GMO_001001",
          componentName: "Distilled water",
          componentLabel: "Distilled water",
          concValue: "",
          concUnit: "",
          volume: "738",
          unit: "ml",
          referenceMediaId: "",
        },
        {
          id: "GMO_001003",
          componentName: "Yeast extract",
          componentLabel: "Yeast extract",
          concValue: "",
          concUnit: "",
          volume: "1",
          unit: "g",
          referenceMediaId: "",
        },
        {
          id: "GMO_001006",
          componentName: "KH2PO4",
          componentLabel: "Potassium phosphate monobasic",
          concValue: "",
          concUnit: "",
          volume: "1.5",
          unit: "g",
          referenceMediaId: "",
        },
        {
          id: "GMO_001008",
          componentName: "NH4Cl",
          componentLabel: "Ammonium chloride",
          concValue: "",
          concUnit: "",
          volume: "0.6",
          unit: "g",
          referenceMediaId: "",
        },
        {
          id: "GMO_001013",
          componentName: "MgCl2·6H2O",
          componentLabel: "Magnesium chloride hexahydrate",
          concValue: "",
          concUnit: "",
          volume: "0.4",
          unit: "g",
          referenceMediaId: "",
        },
        {
          id: "GMO_001045",
          componentName: "Na2CO3",
          componentLabel: "Sodium carbonate",
          concValue: "",
          concUnit: "",
          volume: "4",
          unit: "g",
          referenceMediaId: "",
        },
        {
          id: "GMO_001057",
          componentName: "Na2WO4·2H2O",
          componentLabel: "Sodium tungstate dihydrate",
          concValue: "",
          concUnit: "",
          volume: "0.4",
          unit: "mg",
          referenceMediaId: "",
        },
        {
          id: "GMO_001115",
          componentName: "Na2HPO4·12H2O",
          componentLabel: "Disodium phosphate dodecahydrate",
          concValue: "",
          concUnit: "",
          volume: "4.2",
          unit: "g",
          referenceMediaId: "",
        },
        {
          id: "GMO_001043",
          componentName: "Bacto Tryptone (Difco)",
          componentLabel: "Bacto &trade; Tryptone",
          concValue: "",
          concUnit: "",
          volume: "1",
          unit: "g",
          referenceMediaId: "",
        },
        {
          id: "",
          componentName: "Wolfe's modified mineral solution*",
          componentLabel: "",
          concValue: "",
          concUnit: "",
          volume: "50",
          unit: "ml",
          referenceMediaId: "",
        },
        {
          id: "",
          componentName: "VFA**",
          componentLabel: "",
          concValue: "",
          concUnit: "",
          volume: "1",
          unit: "ml",
          referenceMediaId: "",
        },
        {
          id: "GMO_001903",
          componentName: "KOH",
          componentLabel: "Potassium hydroxide solution",
          concValue: "10",
          concUnit: "N",
          volume: "",
          unit: "",
          referenceMediaId: "",
        },
      ],
    },
    {
      index: 2,
      comment: "pH 6.5",
    },
    {
      index: 3,
      comment: "&nbsp;",
    },
    {
      index: 4,
      comment: "Adjust pH to 6.5 with 10 N KOH and add the following medium.",
    },
    {
      index: 5,
      name: "main solution 2",
      items: [
        {
          id: "GMO_001403",
          componentName: "0.1% Resazurin solution",
          componentLabel: "Resazurin solution",
          concValue: "0.1",
          concUnit: "%",
          volume: "1",
          unit: "ml",
          referenceMediaId: "",
        },
        {
          id: "GMO_001137",
          componentName: "Cellobiose",
          componentLabel: "Cellobiose",
          concValue: "",
          concUnit: "",
          volume: "0.2",
          unit: "g",
          referenceMediaId: "",
        },
        {
          id: "GMO_001814",
          componentName: "myo-Inositol",
          componentLabel: "myo-Inositol",
          concValue: "",
          concUnit: "",
          volume: "1",
          unit: "mg",
          referenceMediaId: "",
        },
        {
          id: "",
          componentName: "Vitamin mixture***",
          componentLabel: "",
          concValue: "",
          concUnit: "",
          volume: "10",
          unit: "ml",
          referenceMediaId: "",
        },
        {
          id: "",
          componentName: "Cellulose****",
          componentLabel: "",
          concValue: "",
          concUnit: "",
          volume: "200",
          unit: "ml",
          referenceMediaId: "",
        },
        {
          id: "GMO_002261",
          componentName: "N2 gas",
          componentLabel: "Nitrogen gas",
          concValue: "",
          concUnit: "",
          volume: "",
          unit: "",
          referenceMediaId: "",
        },
      ],
    },
    {
      index: 6,
      comment: "&nbsp;",
    },
    {
      index: 7,
      comment:
        "Heat the above mixed solution at 60℃ for 5 to 10 min and then bubble with N2 gas. And then add the following ingredients.",
    },
    {
      index: 8,
      name: "main solution 3",
      items: [
        {
          id: "GMO_001014",
          componentName: "Na2S·9H2O",
          componentLabel: "Sodium sulfide nonahydrate",
          concValue: "",
          concUnit: "",
          volume: "0.5",
          unit: "g",
          referenceMediaId: "",
        },
        {
          id: "GMO_001318",
          componentName: "Cysteine",
          componentLabel: "Cysteine",
          concValue: "",
          concUnit: "",
          volume: "0.5",
          unit: "g",
          referenceMediaId: "",
        },
        {
          id: "GMO_001007",
          componentName: "Agar (if needed)",
          componentLabel: "Agar",
          concValue: "",
          concUnit: "",
          volume: "15",
          unit: "g",
          referenceMediaId: "",
        },
      ],
    },
    {
      index: 9,
      comment: "&nbsp;",
    },
    {
      index: 10,
      comment: "Under anaerobic condition, the medium is autoclaved at 100℃ for 10 min.",
    },
    {
      index: 11,
      comment: "&nbsp;",
    },
    {
      index: 12,
      name: "*Wolfe's modified mineral solution",
      items: [
        {
          id: "GMO_001001",
          componentName: "Distilled water",
          componentLabel: "Distilled water",
          concValue: "",
          concUnit: "",
          volume: "1",
          unit: "L",
          referenceMediaId: "",
        },
        {
          id: "GMO_001002",
          componentName: "MgSO4·7H2O",
          componentLabel: "Magnesium sulfate heptahydrate",
          concValue: "",
          concUnit: "",
          volume: "3",
          unit: "g",
          referenceMediaId: "",
        },
        {
          id: "GMO_001004",
          componentName: "NaCl",
          componentLabel: "Sodium chloride",
          concValue: "",
          concUnit: "",
          volume: "1",
          unit: "g",
          referenceMediaId: "",
        },
        {
          id: "GMO_001011",
          componentName: "Na2MoO4·2H2O",
          componentLabel: "Sodium molybdate dihydrate",
          concValue: "",
          concUnit: "",
          volume: "0.01",
          unit: "g",
          referenceMediaId: "",
        },
        {
          id: "GMO_001015",
          componentName: "Boric acid",
          componentLabel: "Boric acid",
          concValue: "",
          concUnit: "",
          volume: "0.01",
          unit: "g",
          referenceMediaId: "",
        },
        {
          id: "GMO_001016",
          componentName: "FeSO4·7H2O",
          componentLabel: "Iron(II) sulfate heptahydrate",
          concValue: "",
          concUnit: "",
          volume: "0.1",
          unit: "g",
          referenceMediaId: "",
        },
        {
          id: "GMO_001023",
          componentName: "ZnSO4·7H2O",
          componentLabel: "Zinc sulfate heptahydrate",
          concValue: "",
          concUnit: "",
          volume: "0.1",
          unit: "g",
          referenceMediaId: "",
        },
        {
          id: "GMO_001039",
          componentName: "CuSO4·5H2O",
          componentLabel: "Copper(II) sulfate pentahydrate",
          concValue: "",
          concUnit: "",
          volume: "0.01",
          unit: "g",
          referenceMediaId: "",
        },
        {
          id: "GMO_001053",
          componentName: "Nitrilotriacetic acid (NTA)",
          componentLabel: "Nitrilotriacetic acid",
          concValue: "",
          concUnit: "",
          volume: "1.5",
          unit: "g",
          referenceMediaId: "",
        },
        {
          id: "GMO_001061",
          componentName: "CaCl2",
          componentLabel: "Calcium chloride",
          concValue: "",
          concUnit: "",
          volume: "0.1",
          unit: "g",
          referenceMediaId: "",
        },
        {
          id: "GMO_001081",
          componentName: "MnSO4·H2O",
          componentLabel: "Manganese sulfate monohydrate",
          concValue: "",
          concUnit: "",
          volume: "0.5",
          unit: "g",
          referenceMediaId: "",
        },
        {
          id: "GMO_001110",
          componentName: "Co(NO3)2·6H2O",
          componentLabel: "Cobalt(II) nitrate hexahydrate",
          concValue: "",
          concUnit: "",
          volume: "0.1",
          unit: "g",
          referenceMediaId: "",
        },
        {
          id: "GMO_001093",
          componentName: "Na2SeO3",
          componentLabel: "Sodium selenite",
          concValue: "",
          concUnit: "",
          volume: "0.001",
          unit: "g",
          referenceMediaId: "",
        },
        {
          id: "GMO_001903",
          componentName: "KOH",
          componentLabel: "Potassium hydroxide solution",
          concValue: "2",
          concUnit: "N",
          volume: "",
          unit: "",
          referenceMediaId: "",
        },
      ],
    },
    {
      index: 13,
      comment:
        "Nitrilotriacetic acid is suspended in 500 ml water, and dissolved by titrating with 2 N KOH until its pH stabilize at 6.5. The rest of the ingredients are added and dissolved. Finally total volume is adjusted to 1 L.",
    },
    {
      index: 14,
      comment: "&nbsp;",
    },
    {
      index: 15,
      name: "**VFA",
      items: [
        {
          id: "GMO_001175",
          componentName: "DL-α-Methylbutyric acid",
          componentLabel: "DL-alpha-Methylbutyric acid",
          concValue: "",
          concUnit: "",
          volume: "1",
          unit: "ml",
          referenceMediaId: "",
        },
        {
          id: "GMO_001178",
          componentName: "Butyric acid",
          componentLabel: "Butyric acid",
          concValue: "",
          concUnit: "",
          volume: "4",
          unit: "ml",
          referenceMediaId: "",
        },
        {
          id: "GMO_001179",
          componentName: "Acetic acid",
          componentLabel: "Acetic acid",
          concValue: "",
          concUnit: "",
          volume: "17",
          unit: "ml",
          referenceMediaId: "",
        },
        {
          id: "GMO_001181",
          componentName: "n-Valeric acid",
          componentLabel: "Valeric acid",
          concValue: "",
          concUnit: "",
          volume: "1",
          unit: "ml",
          referenceMediaId: "",
        },
        {
          id: "GMO_001182",
          componentName: "iso-Valeric acid",
          componentLabel: "Isovaleric acid",
          concValue: "",
          concUnit: "",
          volume: "1",
          unit: "ml",
          referenceMediaId: "",
        },
        {
          id: "GMO_001184",
          componentName: "iso-Butyric acid",
          componentLabel: "Isobutyric acid",
          concValue: "",
          concUnit: "",
          volume: "1",
          unit: "ml",
          referenceMediaId: "",
        },
        {
          id: "GMO_001192",
          componentName: "Propionic acid",
          componentLabel: "Propionic acid",
          concValue: "",
          concUnit: "",
          volume: "6",
          unit: "ml",
          referenceMediaId: "",
        },
      ],
    },
    {
      index: 16,
      comment: "&nbsp;",
    },
    {
      index: 17,
      name: "***Vitamin mixture",
      items: [
        {
          id: "GMO_001001",
          componentName: "Distilled water",
          componentLabel: "Distilled water",
          concValue: "",
          concUnit: "",
          volume: "1",
          unit: "L",
          referenceMediaId: "",
        },
        {
          id: "GMO_001025",
          componentName: "Biotin",
          componentLabel: "Biotin",
          concValue: "",
          concUnit: "",
          volume: "0.2",
          unit: "mg",
          referenceMediaId: "",
        },
        {
          id: "GMO_001026",
          componentName: "p-Aminobenzoic acid",
          componentLabel: "4-Aminobenzoic acid",
          concValue: "",
          concUnit: "",
          volume: "20",
          unit: "mg",
          referenceMediaId: "",
        },
        {
          id: "GMO_001027",
          componentName: "Thiamin-HCl",
          componentLabel: "Thiamine hydrochloride",
          concValue: "",
          concUnit: "",
          volume: "20",
          unit: "mg",
          referenceMediaId: "",
        },
        {
          id: "GMO_001028",
          componentName: "Ca-pantothenate",
          componentLabel: "Calcium pantothenate",
          concValue: "",
          concUnit: "",
          volume: "40",
          unit: "mg",
          referenceMediaId: "",
        },
        {
          id: "GMO_001029",
          componentName: "Pyridoxine-HCl",
          componentLabel: "Pyridoxine hydrochloride",
          concValue: "",
          concUnit: "",
          volume: "40",
          unit: "mg",
          referenceMediaId: "",
        },
        {
          id: "GMO_001033",
          componentName: "Folic acid",
          componentLabel: "Folic acid",
          concValue: "",
          concUnit: "",
          volume: "0.2",
          unit: "mg",
          referenceMediaId: "",
        },
        {
          id: "GMO_001034",
          componentName: "Cyanocobalamin",
          componentLabel: "Cobalamin",
          concValue: "",
          concUnit: "",
          volume: "2",
          unit: "ug",
          referenceMediaId: "",
        },
        {
          id: "GMO_001037",
          componentName: "Riboflavin",
          componentLabel: "Riboflavin",
          concValue: "",
          concUnit: "",
          volume: "40",
          unit: "mg",
          referenceMediaId: "",
        },
        {
          id: "GMO_001038",
          componentName: "Niacin",
          componentLabel: "Nicotinic acid",
          concValue: "",
          concUnit: "",
          volume: "40",
          unit: "mg",
          referenceMediaId: "",
        },
        {
          id: "GMO_001099",
          componentName: "Choline chloride",
          componentLabel: "Choline chloride",
          concValue: "",
          concUnit: "",
          volume: "100",
          unit: "mg",
          referenceMediaId: "",
        },
        {
          id: "GMO_001814",
          componentName: "myo-Inositol",
          componentLabel: "myo-Inositol",
          concValue: "",
          concUnit: "",
          volume: "200",
          unit: "mg",
          referenceMediaId: "",
        },
      ],
    },
    {
      index: 18,
      comment: "&nbsp;",
    },
    {
      index: 19,
      comment: "****3% Cellulose suspension which is ball-milled for 3 days.",
    },
    {
      index: 20,
      name: "****Cellulose",
      items: [
        {
          id: "GMO_001001",
          componentName: "Distilled water",
          componentLabel: "Distilled water",
          concValue: "",
          concUnit: "",
          volume: "1",
          unit: "L",
          referenceMediaId: "",
        },
        {
          id: "GMO_001180",
          componentName: "Cellulose",
          componentLabel: "Cellulose",
          concValue: "",
          concUnit: "",
          volume: "30",
          unit: "g",
          referenceMediaId: "",
        },
      ],
    },
  ],
};
