import { AllComponentsResponse } from "./types";

export const allComponentsResponse: AllComponentsResponse = [
  {
    name: "Hexahydro-1H-1,4-diazepine-1,4-bis(2-ethanesulfonic acid) solution; HomoPIPES solution, HomoPIPES solution",
    gmoid: "GMO_001925",
  },
  { name: "Disodium phosphate-Potassium phosphate monobasic buffer", gmoid: "GMO_001470" },
  { name: "1,1,2-Trichloroethane; Beta-trichloroethane", gmoid: "GMO_001731" },
  { name: "1,2-Dichloropropane", gmoid: "GMO_001732" },
  { name: "1,2-Dichloropropane methanol solution", gmoid: "GMO_001757" },
  { name: "10xCMD stock solution", gmoid: "GMO_001917" },
  { name: "2,3-Butanediol", gmoid: "GMO_001240" },
  { name: "2-Mercaptoethanol", gmoid: "GMO_001701" },
  { name: "2-Methylbutanoic acid", gmoid: "GMO_001495" },
  { name: "3-Chloro-4-hydroxyphenylacetic acid", gmoid: "GMO_001945" },
  { name: "4-Aminobenzoic acid; PABA, para-aminobenzoic acid", gmoid: "GMO_001026" },
  { name: "5-Methyl-2'-deoxycytidine; 5-Methyldeoxycytidine", gmoid: "GMO_001863" },
  { name: "ABCM agar (Eiken)", gmoid: "GMO_001348" },
  { name: "ACES; ACES buffer, N-(2-Acetamido)-2-aminoethanesulfonic acid", gmoid: "GMO_001860" },
  { name: "Acetate", gmoid: "GMO_001926" },
  { name: "Acetic acid", gmoid: "GMO_001179" },
  { name: "Acetoin; 3-hydroxybutanone, Acetyl methyl carbinol", gmoid: "GMO_001391" },
  { name: "Acid hydrolysates of casein", gmoid: "GMO_001867" },
  { name: "Activated carbon", gmoid: "GMO_001289" },
  { name: "Adenine sulfate", gmoid: "GMO_001398" },
  { name: "Agar", gmoid: "GMO_001007" },
  { name: "Aged seawater", gmoid: "GMO_001744" },
  { name: "Alanine", gmoid: "GMO_001765" },
  { name: "Allantoin; 5-Ureidohydantoin, Glyoxyldiureide", gmoid: "GMO_001375" },
  { name: "Aluminum chloride", gmoid: "GMO_001255" },
  { name: "Aluminum chloride hexahydrate", gmoid: "GMO_001511" },
  { name: "Aluminum potassium sulfate", gmoid: "GMO_001088" },
  { name: "Aluminum potassium sulfate dodecahydrate", gmoid: "GMO_001051" },
  { name: "Aluminum potassium sulfate dodecahydrate solution", gmoid: "GMO_001504" },
  { name: "Ammonium acetate", gmoid: "GMO_001141" },
  { name: "Ammonium bicarbonate", gmoid: "GMO_001281" },
  { name: "Ammonium bicarbonate solution", gmoid: "GMO_001458" },
  { name: "Ammonium chloride", gmoid: "GMO_001008" },
  { name: "Ammonium chloride solution", gmoid: "GMO_001394" },
  { name: "Ammonium citrate", gmoid: "GMO_001208" },
  { name: "Ammonium dihydrogen phosphate", gmoid: "GMO_001214" },
  { name: "Ammonium ferric citrate", gmoid: "GMO_001147" },
  { name: "Ammonium ferric citrate solution", gmoid: "GMO_001454" },
  { name: "Ammonium hydrogen phosphate; DAP, Diammonium phosphate", gmoid: "GMO_001379" },
  {
    name: "Ammonium iron(II) sulfate; Ferrous ammonium sulfate, Iron(II) ammonium sulfate",
    gmoid: "GMO_001869",
  },
  { name: "Ammonium iron(II) sulfate heptahydrate", gmoid: "GMO_001128" },
  {
    name: "Ammonium iron(II) sulfate hexahydrate; Ferrous ammonium sulfate hexahydrate, Iron(II) ammonium sulfate hexahydrate",
    gmoid: "GMO_001076",
  },
  { name: "Ammonium iron(II) sulfate hexahydrate solution", gmoid: "GMO_001455" },
  { name: "Ammonium iron(II) sulfate solution", gmoid: "GMO_001698" },
  { name: "Ammonium nitrate", gmoid: "GMO_001100" },
  { name: "Ammonium sulfate", gmoid: "GMO_001030" },
  { name: "Ammonium sulfate heptahydrate", gmoid: "GMO_001209" },
  { name: "Ammonium tartrate", gmoid: "GMO_001361" },
  { name: "Ampicillin solution", gmoid: "GMO_001512" },
  { name: "Anaerobic water", gmoid: "GMO_001513" },
  { name: "Arabinose", gmoid: "GMO_001350" },
  { name: "Arginine", gmoid: "GMO_001203" },
  { name: "Artificial seawater", gmoid: "GMO_001235" },
  { name: "Artificial seawater with gravimetric salts", gmoid: "GMO_001880" },
  { name: "Artificial seawater with volumetric salts", gmoid: "GMO_001881" },
  { name: "Ascorbic acid", gmoid: "GMO_001247" },
  { name: "Ascorbic acid solution", gmoid: "GMO_001500" },
  { name: "Asparagine", gmoid: "GMO_001190" },
  { name: "Aspartic acid", gmoid: "GMO_001769" },
  { name: "Autolyzed Yeast Extract (15% solution)", gmoid: "GMO_001314" },
  { name: "BBL BCYE agar base", gmoid: "GMO_001514" },
  { name: "BBL Brucella agar", gmoid: "GMO_001522" },
  { name: "BBL Corn meal agar", gmoid: "GMO_001539" },
  { name: "BBL Fluid thioglycollate medium", gmoid: "GMO_001555" },
  { name: "BBL Phytone peptone", gmoid: "GMO_001622" },
  { name: "BBL Polypeptone peptone", gmoid: "GMO_001424" },
  { name: "BBL Trypticase peptone; BBL &trade; Trypticase &trade; peptone", gmoid: "GMO_001097" },
  { name: "BBL Trypticase peptone solution", gmoid: "GMO_001735" },
  { name: "BBL Trypticase soy broth", gmoid: "GMO_001438" },
  { name: "BCYE agar; Buffered charcoal yeast extract agar", gmoid: "GMO_001847" },
  { name: "BL agar (Nissui); Glucose blood liver agar", gmoid: "GMO_001320" },
  { name: "Bacteriological peptone", gmoid: "GMO_001399" },
  { name: "Bacto &trade; TC yeastolate", gmoid: "GMO_001657" },
  { name: "Bacto Casamino acids (Difco)", gmoid: "GMO_001705" },
  { name: "Bacto Neopeptone", gmoid: "GMO_001610" },
  { name: "Bacto Proteose peptone", gmoid: "GMO_001626" },
  { name: "Bacto Proteose peptone No. 3", gmoid: "GMO_001144" },
  { name: "Bacto Soytone", gmoid: "GMO_001197" },
  { name: "Bacto Tryptic soy broth", gmoid: "GMO_001117" },
  { name: "Bacto Tryptic soy broth without dextrose", gmoid: "GMO_001287" },
  { name: "Bacto Tryptone; Tryptone, Bacto &trade;", gmoid: "GMO_001043" },
  { name: "Bacto Tryptose", gmoid: "GMO_001673" },
  { name: "Bacto Tryptose phosphate broth (Difco)", gmoid: "GMO_001674" },
  {
    name: "Bacto Yeast extract; Bacto &trade; Yeast extract, Yeast Extract, Bacto &trade;",
    gmoid: "GMO_001018",
  },
  { name: "Bacto Yeast extract solution", gmoid: "GMO_001736" },
  { name: "Bacto agar", gmoid: "GMO_001130" },
  { name: "Bacto blood agar base", gmoid: "GMO_001297" },
  { name: "Bacto brain heart infusion; Bacto &trade; brain heart infusion", gmoid: "GMO_001149" },
  { name: "Bacto casitone; Casitone", gmoid: "GMO_001104" },
  { name: "Bacto heart infusion broth", gmoid: "GMO_001146" },
  { name: "Bacto malt extract", gmoid: "GMO_001159" },
  { name: "Bacto peptone", gmoid: "GMO_001089" },
  { name: "Bacto todd hewitt broth", gmoid: "GMO_001254" },
  { name: "Bacto tryptone solution", gmoid: "GMO_001737" },
  { name: "Bacto yeast nitrogen base without amino acids", gmoid: "GMO_001194" },
  { name: "Baker's yeast", gmoid: "GMO_001427" },
  { name: "Barium chloride", gmoid: "GMO_001515" },
  { name: "Barium chloride dihydrate", gmoid: "GMO_001516" },
  { name: "Beef brain powder", gmoid: "GMO_001518" },
  { name: "Beef extract", gmoid: "GMO_001072" },
  { name: "Beef extract (BD)", gmoid: "GMO_001442" },
  { name: "Benzene solution", gmoid: "GMO_001497" },
  { name: "Beta-NAD; NAD, NAD+, Nicotinamide adenine dinucleotide", gmoid: "GMO_001691" },
  {
    name: "Beta-NADP sodium salt; Beta-NADP-Na, β-Nicotinamide adenine dinucleotide phosphate sodium salt, Beta-Nicotinamide adenine dinucleotide phosphate sodium salt",
    gmoid: "GMO_001817",
  },
  { name: "Betaine", gmoid: "GMO_001748" },
  { name: "Betaine solution", gmoid: "GMO_001479" },
  { name: "Biotin; Coenzyme R, Vitamin B7, Vitamin H", gmoid: "GMO_001025" },
  { name: "Biphenyl", gmoid: "GMO_001383" },
  { name: "Bis-tris propane; 1,3-bis(tris(hydroxymethyl)methylamino)propane", gmoid: "GMO_001219" },
  { name: "Blood-derived component", gmoid: "GMO_001893" },
  { name: "Bonito extract", gmoid: "GMO_001246" },
  {
    name: "Borax; Borax decahydrate, Disodium tetraborate decahydrate, Sodium borate decahydrate, Sodium tetraborate decahydrate",
    gmoid: "GMO_001598",
  },
  { name: "Boric acid", gmoid: "GMO_001015" },
  {
    name: "Bovine serum albumin; BSA, Bovine serum albumin fraction V, Fraction V",
    gmoid: "GMO_001520",
  },
  { name: "Bovine serum albumin fraction V (Roche)", gmoid: "GMO_001333" },
  { name: "Bovine serum albumin fraction V (Wako) ", gmoid: "GMO_001702" },
  { name: "Brewer anaerobic agar (Difco)", gmoid: "GMO_001521" },
  { name: "Bromophenol blue", gmoid: "GMO_001351" },
  { name: "Bromophenol blue solution", gmoid: "GMO_001901" },
  { name: "Brown rice flakes", gmoid: "GMO_001345" },
  { name: "Butyric acid; Butanoic acid", gmoid: "GMO_001178" },
  { name: "CAPSO; 3-(cyclohexylamino)-2-hydroxy-1-propanesulfonic acid", gmoid: "GMO_001704" },
  { name: "CMRL 1066; Connaugh Medical Research Laboratories 1066 medium", gmoid: "GMO_001849" },
  { name: "CMRL 1066 (Gibco 330-1540)", gmoid: "GMO_001523" },
  { name: "CMRL 1066 with glutamate (Sigma)", gmoid: "GMO_001524" },
  { name: "Calcium carbonate", gmoid: "GMO_001063" },
  { name: "Calcium chloride", gmoid: "GMO_001061" },
  { name: "Calcium chloride anhydrate", gmoid: "GMO_001819" },
  { name: "Calcium chloride dihydrate", gmoid: "GMO_001005" },
  { name: "Calcium chloride dihydrate solution", gmoid: "GMO_001228" },
  { name: "Calcium chloride hexahydrate", gmoid: "GMO_001163" },
  { name: "Calcium chloride hexahydrate solution", gmoid: "GMO_001459" },
  { name: "Calcium chloride monohydrate", gmoid: "GMO_001232" },
  { name: "Calcium chloride solution", gmoid: "GMO_001357" },
  { name: "Calcium folinate; Calcium folinic acid, Leucovorin", gmoid: "GMO_001526" },
  { name: "Calcium lactate", gmoid: "GMO_001305" },
  { name: "Calcium malate", gmoid: "GMO_001527" },
  { name: "Calcium nitrate", gmoid: "GMO_001193" },
  { name: "Calcium nitrate tetrahydrate", gmoid: "GMO_001116" },
  { name: "Calcium pantothenate", gmoid: "GMO_001028" },
  { name: "Calcium sulfate", gmoid: "GMO_001882" },
  { name: "Calcium sulfate dihydrate", gmoid: "GMO_001087" },
  { name: "Calcium sulfate heptahydrate", gmoid: "GMO_001525" },
  { name: "Carboxymethyl cellulose; CMC, Carmellose", gmoid: "GMO_001284" },
  { name: "Carrot", gmoid: "GMO_001212" },
  { name: "Casamino acid", gmoid: "GMO_001113" },
  { name: "Casamino acid solution", gmoid: "GMO_001483" },
  { name: "Casein", gmoid: "GMO_001531" },
  { name: "Casein (Sigma)", gmoid: "GMO_001316" },
  { name: "Casein peptone", gmoid: "GMO_001245" },
  { name: "Casein sodium; Casein sodium salt, Sodium caseinate", gmoid: "GMO_001402" },
  { name: "Catalase", gmoid: "GMO_001343" },
  { name: "Catalase from bovine liver C-10 (Sigma)", gmoid: "GMO_001532" },
  { name: "Cellobiose", gmoid: "GMO_001137" },
  { name: "Cellobiose solution", gmoid: "GMO_001484" },
  { name: "Cellulose", gmoid: "GMO_001180" },
  { name: "Cellulose (MN 300)", gmoid: "GMO_001222" },
  { name: "Chalcopyrite", gmoid: "GMO_001533" },
  { name: "Charcoal", gmoid: "GMO_001896" },
  { name: "Cheese whey", gmoid: "GMO_001259" },
  { name: "Chitosan", gmoid: "GMO_001412" },
  { name: "Chloramphenicol", gmoid: "GMO_001347" },
  { name: "Cholesterol; Cholesterin", gmoid: "GMO_001821" },
  { name: "Choline chloride", gmoid: "GMO_001099" },
  { name: "Chrysalis extract", gmoid: "GMO_001282" },
  { name: "Citric acid", gmoid: "GMO_001112" },
  { name: "Cobalamin; Vitamin B12", gmoid: "GMO_001034" },
  { name: "Cobalamin solution; Vitamin B12 solution", gmoid: "GMO_001106" },
  { name: "Cobalt dichloride; Cobalt(II) chloride", gmoid: "GMO_001309" },
  { name: "Cobalt dichloride hexahydrate; Cobalt(II) chloride hexahydrate", gmoid: "GMO_001021" },
  { name: "Cobalt dichloride hexahydrate solution ", gmoid: "GMO_001922" },
  { name: "Cobalt dichloride monohydrate", gmoid: "GMO_001745" },
  { name: "Cobalt dichloride solution; Cobalt(II) chloride solution", gmoid: "GMO_001535" },
  { name: "Cobalt(II) nitrate", gmoid: "GMO_001883" },
  { name: "Cobalt(II) nitrate hexahydrate; Cobalt nitrate hexahydrate", gmoid: "GMO_001110" },
  { name: "Cobalt(II) sulfate heptahydrate", gmoid: "GMO_001050" },
  { name: "Coenzyme A", gmoid: "GMO_001536" },
  { name: "Coenzyme A sodium salt", gmoid: "GMO_001822" },
  { name: "Coenzyme M; Mercaptoethanesulfonic acid", gmoid: "GMO_001165" },
  { name: "Coenzyme M solution; Mercaptoethanesulfonic acid solution", gmoid: "GMO_001481" },
  { name: "Congo red", gmoid: "GMO_001537" },
  { name: "Copper(II) chloride; Cupric chloride", gmoid: "GMO_001542" },
  { name: "Copper(II) chloride dihydrate; Cupric chloride dihydrate", gmoid: "GMO_001024" },
  { name: "Copper(II) chloride hexahydrate", gmoid: "GMO_001755" },
  { name: "Copper(II) chloride monohydrate", gmoid: "GMO_001746" },
  { name: "Copper(II) sulfate; Copper sulfate, Cupric sulfate", gmoid: "GMO_001103" },
  { name: "Copper(II) sulfate dihydrate; Cupric sulfate dihydrate", gmoid: "GMO_001754" },
  { name: "Copper(II) sulfate heptahydrate; Boothite", gmoid: "GMO_001761" },
  { name: "Copper(II) sulfate heptahydrate solution", gmoid: "GMO_001366" },
  { name: "Copper(II) sulfate pentahydrate; Cupric sulfate pentahydrate", gmoid: "GMO_001039" },
  { name: "Copper(II) sulfate pentahydrate solution", gmoid: "GMO_001476" },
  { name: "Corn and fish meal mixture (feed for birds)", gmoid: "GMO_001365" },
  { name: "Corn starch", gmoid: "GMO_001929" },
  { name: "Corn steep liquor", gmoid: "GMO_001540" },
  { name: "Cornmeal extract", gmoid: "GMO_001157" },
  { name: "Cow manure", gmoid: "GMO_001301" },
  { name: "Cow's milk (whole fat)", gmoid: "GMO_001541" },
  { name: "Creatine", gmoid: "GMO_001706" },
  { name: "Crotonic acid", gmoid: "GMO_001294" },
  { name: "Crotonic acid solution", gmoid: "GMO_001918" },
  { name: "Cycloheximide", gmoid: "GMO_001275" },
  { name: "Cysteine", gmoid: "GMO_001318" },
  { name: "Cysteine hydrochloride", gmoid: "GMO_001032" },
  { name: "Cysteine hydrochloride solution", gmoid: "GMO_001827" },
  { name: "Cysteine solution", gmoid: "GMO_001485" },
  { name: "Cytidine", gmoid: "GMO_001422" },
  { name: "D-Alanine", gmoid: "GMO_001370" },
  { name: "D-Arginine", gmoid: "GMO_001768" },
  { name: "D-Asparagine", gmoid: "GMO_001871" },
  { name: "D-Aspartic acid", gmoid: "GMO_001771" },
  { name: "D-Cystine", gmoid: "GMO_001772" },
  { name: "D-Fructose", gmoid: "GMO_001123" },
  { name: "D-Fructose solution", gmoid: "GMO_001464" },
  { name: "D-Galactose", gmoid: "GMO_001876" },
  { name: "D-Glucose; Dextrose, grape sugar", gmoid: "GMO_001010" },
  { name: "D-Glucose (anhydrous); Dextrose (anhydrous), Glucose (anhydrous)", gmoid: "GMO_001826" },
  { name: "D-Glucuronic acid sodium salt", gmoid: "GMO_001865" },
  { name: "D-Glutamic acid", gmoid: "GMO_001774" },
  { name: "D-Glutamine", gmoid: "GMO_001777" },
  { name: "D-Histidine", gmoid: "GMO_001873" },
  { name: "D-Isoleucine", gmoid: "GMO_001784" },
  { name: "D-Leucine", gmoid: "GMO_001786" },
  { name: "D-Lysine", gmoid: "GMO_001789" },
  { name: "D-Methionine ", gmoid: "GMO_001792" },
  { name: "D-Pantothenic Acid hemicalcium salt", gmoid: "GMO_001816" },
  { name: "D-Phenylalanine ", gmoid: "GMO_001795" },
  { name: "D-Proline", gmoid: "GMO_001798" },
  { name: "D-Serine", gmoid: "GMO_001801" },
  { name: "D-Threonine", gmoid: "GMO_001804" },
  { name: "D-Tryptophan", gmoid: "GMO_001806" },
  { name: "D-Tyrosine", gmoid: "GMO_001809" },
  { name: "D-Valine", gmoid: "GMO_001812" },
  { name: "DL-Methionine; LD-Methionine", gmoid: "GMO_001327" },
  { name: "DL-Tryptophan; LD-Tryptophan", gmoid: "GMO_001385" },
  { name: "DL-alpha-Methylbutyric acid", gmoid: "GMO_001175" },
  { name: "Daigo's IMK medium (Nihon seiyaku)", gmoid: "GMO_001243" },
  { name: "Decane", gmoid: "GMO_001707" },
  { name: "Defibrinated horse blood", gmoid: "GMO_001439" },
  {
    name: "Deionized water; DI water, DM water, De-ionized water, Demineralized water",
    gmoid: "GMO_001695",
  },
  { name: "Demineralized Water", gmoid: "GMO_001930" },
  { name: "Deoxyadenosine; 2'-Deoxyadenosine", gmoid: "GMO_001823" },
  { name: "Deoxycytidine hydrochloride; 2′-Deoxycytidine hydrochloride", gmoid: "GMO_001825" },
  { name: "Deoxyguanosine; 2'-Deoxyguanosine", gmoid: "GMO_001824" },
  { name: "Dextrin", gmoid: "GMO_001268" },
  { name: "Diammonium hydrogen citrate", gmoid: "GMO_001084" },
  { name: "Dichloran", gmoid: "GMO_001414" },
  { name: "Difco Agar, noble", gmoid: "GMO_001510" },
  { name: "Difco Casamino acids, vitamin assay", gmoid: "GMO_001169" },
  { name: "Difco ISP medium 1; Tryptone-Yeast Extract Broth", gmoid: "GMO_001291" },
  { name: "Difco LB agar, Lennox", gmoid: "GMO_001895" },
  { name: "Difco LB broth, Lennox", gmoid: "GMO_001435" },
  { name: "Difco Lactobacilli MRS broth", gmoid: "GMO_001572" },
  { name: "Difco Legionella agar base", gmoid: "GMO_001848" },
  { name: "Difco Legionella agar enrichment", gmoid: "GMO_001574" },
  { name: "Difco Marine agar 2216", gmoid: "GMO_001295" },
  { name: "Difco Marine broth 2216", gmoid: "GMO_001095" },
  { name: "Difco Nutrient Agar", gmoid: "GMO_001302" },
  { name: "Difco Nutrient broth", gmoid: "GMO_001344" },
  { name: "Difco PPLO Broth; Difco PPLO Broth (w/o CV)", gmoid: "GMO_001183" },
  { name: "Difco YM broth", gmoid: "GMO_001682" },
  { name: "Difco Yeast carbon base", gmoid: "GMO_001392" },
  { name: "Difco heart infusion agar", gmoid: "GMO_001364" },
  { name: "Difco m TGE broth; membrane Tryptone Glucose Extract Broth", gmoid: "GMO_001517" },
  { name: "Difco tryptic soy agar", gmoid: "GMO_001229" },
  { name: "Digested serum", gmoid: "GMO_001850" },
  { name: "Dimethyl sulfoxide", gmoid: "GMO_001544" },
  { name: "Disodio persulfide nonahydrate", gmoid: "GMO_001601" },
  { name: "Disodium EDTA", gmoid: "GMO_001058" },
  { name: "Disodium EDTA dihydrate", gmoid: "GMO_001148" },
  { name: "Disodium fumarate", gmoid: "GMO_001298" },
  { name: "Disodium fumarate solution", gmoid: "GMO_001729" },
  { name: "Disodium phosphate", gmoid: "GMO_001069" },
  { name: "Disodium phosphate dihydrate", gmoid: "GMO_001155" },
  { name: "Disodium phosphate dodecahydrate", gmoid: "GMO_001115" },
  {
    name: "Disodium phosphate heptahydrate; Disodium hydrogen phosphate heptahydrate",
    gmoid: "GMO_001189",
  },
  { name: "Disodium phosphate hexahydrate", gmoid: "GMO_001599" },
  { name: "Disodium phosphate solution", gmoid: "GMO_001505" },
  { name: "Disodium phosphate-Monosodium phosphate buffer", gmoid: "GMO_001600" },
  { name: "Disodium selenate", gmoid: "GMO_001111" },
  { name: "Disodium succinate", gmoid: "GMO_001177" },
  {
    name: "Disodium sulfide-Cysteine solution; Sodium sulfide-Cysteine solution",
    gmoid: "GMO_001373",
  },
  { name: "Disodium tetraborate", gmoid: "GMO_001187" },
  { name: "Distilled water", gmoid: "GMO_001001" },
  { name: "Dithionite", gmoid: "GMO_001261" },
  { name: "Dithionite solution", gmoid: "GMO_001279" },
  { name: "Dithiothreitol; DTT", gmoid: "GMO_001545" },
  { name: "Dithiothreitol solution", gmoid: "GMO_001502" },
  { name: "Dried shrimp", gmoid: "GMO_001310" },
  { name: "Dried yeast extract D-3", gmoid: "GMO_001409" },
  { name: "Dried yeast extract S (Wako)", gmoid: "GMO_001546" },
  { name: "Dry yeast", gmoid: "GMO_001260" },
  { name: "EDTA; Ethylenediaminetetraacetic acid", gmoid: "GMO_001237" },
  {
    name: "EDTA monosodium Iron(III) salt ; EDTA-Na-Fe(III), Ethylenediaminetetraacetic acid monosodium iron(III) salt",
    gmoid: "GMO_001759",
  },
  { name: "EDTA monosodium iron(III) solution", gmoid: "GMO_001921" },
  { name: "EDTA solution ", gmoid: "GMO_001920" },
  { name: "Ebios (tablets)", gmoid: "GMO_001226" },
  { name: "Environmental water", gmoid: "GMO_001407" },
  { name: "Estradiol", gmoid: "GMO_001264" },
  { name: "Ethanol; Ethyl alcohol, エチルアルコール", gmoid: "GMO_001114" },
  { name: "Extract", gmoid: "GMO_000011" },
  { name: "FAD; Flavin adenine dinucleotide", gmoid: "GMO_001547" },
  {
    name: "FAD disodium salt; Flavin Adenine Dinucleotide•2Na, Flavin adenine dinucleotide disodium salt",
    gmoid: "GMO_001862",
  },
  { name: "Fe(III)-EDTA", gmoid: "GMO_001139" },
  { name: "Fetal bovine serum", gmoid: "GMO_001552" },
  { name: "Fetal bovine serum (heat-inactivated)", gmoid: "GMO_001397" },
  { name: "Fish meat extract", gmoid: "GMO_001554" },
  { name: "Fluka Fish peptone", gmoid: "GMO_001919" },
  { name: "Folic acid; Folate, Vitamin B9, Vitamin M", gmoid: "GMO_001033" },
  { name: "Fresh baker's yeast extract solution", gmoid: "GMO_001429" },
  { name: "GAM agar (Nissui)", gmoid: "GMO_001556" },
  { name: "GAM agar, modified (Nissui)", gmoid: "GMO_001557" },
  { name: "GAM broth (Nissui)", gmoid: "GMO_001285" },
  { name: "GAM broth, modified (Nissui)", gmoid: "GMO_001858" },
  { name: "Galactose", gmoid: "GMO_001206" },
  { name: "Gelatin", gmoid: "GMO_001395" },
  { name: "Gellan gum", gmoid: "GMO_001250" },
  { name: "Gentisic acid", gmoid: "GMO_001437" },
  { name: "Glacial acetic acid", gmoid: "GMO_001558" },
  { name: "Glucose", gmoid: "GMO_001815" },
  { name: "Glucose solution", gmoid: "GMO_001465" },
  { name: "Glutamate", gmoid: "GMO_001324" },
  { name: "Glutamic acid", gmoid: "GMO_001773" },
  { name: "Glutamine", gmoid: "GMO_001775" },
  { name: "Glutathione", gmoid: "GMO_001328" },
  { name: "Glycerol; Glycerin", gmoid: "GMO_001083" },
  { name: "Glycerol 3-phosphate", gmoid: "GMO_001138" },
  { name: "Glycerol monostearate", gmoid: "GMO_001273" },
  { name: "Glycerol solution", gmoid: "GMO_001466" },
  { name: "Glycine", gmoid: "GMO_001559" },
  { name: "Glycine-Sodium hydroxide buffer", gmoid: "GMO_001461" },
  { name: "Glycylglycine", gmoid: "GMO_001430" },
  { name: "Ground Sesami powder", gmoid: "GMO_001358" },
  { name: "Ground beef (fat free)", gmoid: "GMO_001388" },
  { name: "Guaiacol", gmoid: "GMO_001426" },
  { name: "HEPES; 4-(2-hydroxyethyl)-1-piperazineethanesulfonic acid", gmoid: "GMO_001142" },
  { name: "HEPES (Sigma)", gmoid: "GMO_001749" },
  { name: "HEPES (free acid)", gmoid: "GMO_001750" },
  { name: "HEPES buffer; 4-(2-hydroxyethyl)-1-piperazineethanesulfonic acid", gmoid: "GMO_001738" },
  { name: "Hemin; Hematin", gmoid: "GMO_001312" },
  { name: "Hemin chloride", gmoid: "GMO_001561" },
  { name: "Hemin from bovine solution; Bovine hemin chloride solution", gmoid: "GMO_001519" },
  { name: "Hemin solution", gmoid: "GMO_001449" },
  {
    name: "Hexaammonium heptamolybdate tetrahydrate; AC1LACDZ, Ammonium heptamolybdate tetrahydrate, Ammonium molybdate tetrahydrate",
    gmoid: "GMO_001221",
  },
  { name: "Hexanoic acid; Caproic acid", gmoid: "GMO_001528" },
  { name: "Hipolypepton (Nihon seiyaku); Polypepton", gmoid: "GMO_001322" },
  { name: "Histidine", gmoid: "GMO_001170" },
  {
    name: "Homo-PIPES; HomoPIPES, Homopiperazine-1,4-bis(2-ethanesulfonic acid), Hexahydro-1H-1,4-diazepine-1,4-bis(2-ethanesulfonic acid)",
    gmoid: "GMO_001924",
  },
  { name: "Horse blood", gmoid: "GMO_001562" },
  { name: "Horse serum", gmoid: "GMO_001127" },
  { name: "Humic acid", gmoid: "GMO_001433" },
  { name: "Hunter's basal salts", gmoid: "GMO_001202" },
  { name: "Hy-case amino (Sigma)", gmoid: "GMO_001563" },
  { name: "Hydrochloric acid", gmoid: "GMO_001048" },
  { name: "Hydrochloric acid solution", gmoid: "GMO_001499" },
  { name: "Hydroxyproline", gmoid: "GMO_001779" },
  {
    name: "Indigo carmine; 5,5'-indigodisulfonic acid sodium salt, indigotine",
    gmoid: "GMO_001564",
  },
  { name: "Infusion from Beef heart; Beef heart, infusion from", gmoid: "GMO_001831" },
  { name: "Infusion from Liver; Liver, infusion from", gmoid: "GMO_001145" },
  { name: "Infusion from calf brain; Calf brain, infusion from", gmoid: "GMO_001832" },
  { name: "Infusion from heart muscle; Heart muscle, infusion from", gmoid: "GMO_001834" },
  { name: "Inositol", gmoid: "GMO_001101" },
  { name: "Iron", gmoid: "GMO_001565" },
  { name: "Iron granule", gmoid: "GMO_001410" },
  { name: "Iron stock solution", gmoid: "GMO_001912" },
  { name: "Iron(II) chloride; Ferrous chloride", gmoid: "GMO_001270" },
  { name: "Iron(II) chloride hexahydrate; Iron dichloride hexahydrate", gmoid: "GMO_001549" },
  {
    name: "Iron(II) chloride hexahydrate solution; Iron dichloride hexahydrate solution",
    gmoid: "GMO_001490",
  },
  { name: "Iron(II) chloride solution", gmoid: "GMO_001488" },
  { name: "Iron(II) chloride tetrahydrate; Iron dichloride tetrahydrate", gmoid: "GMO_001548" },
  { name: "Iron(II) citrate; Ferrous citrate", gmoid: "GMO_001716" },
  { name: "Iron(II) sulfate; Ferrous sulfate", gmoid: "GMO_001337" },
  { name: "Iron(II) sulfate heptahydrate; Ferrous sulfate heptahydrate", gmoid: "GMO_001016" },
  {
    name: "Iron(II) sulfate heptahydrate solution; Ferrous sulfate heptahydrate solution",
    gmoid: "GMO_001353",
  },
  { name: "Iron(II) sulfate hexahydrate; Ferrous sulfate hexahydrate", gmoid: "GMO_001550" },
  {
    name: "Iron(II) sulfate hexahydrate solution; Ferrous sulfate hexahydrate solution",
    gmoid: "GMO_001456",
  },
  { name: "Iron(II) sulfate monohydrate; Ferrous sulfate monohydrate", gmoid: "GMO_001551" },
  {
    name: "Iron(II) sulfate pentahydrate solution; Ferrous sulfate pentahydrate solution",
    gmoid: "GMO_001700",
  },
  { name: "Iron(II) sulfate solution; Ferrous sulfate solution", gmoid: "GMO_001393" },
  { name: "Iron(III) chloride; Ferric chloride", gmoid: "GMO_001122" },
  { name: "Iron(III) chloride hexahydrate", gmoid: "GMO_001047" },
  { name: "Iron(III) chloride monohydrate", gmoid: "GMO_001747" },
  { name: "Iron(III) chloride solution", gmoid: "GMO_001715" },
  { name: "Iron(III) chloride tetrahydrate", gmoid: "GMO_001293" },
  { name: "Iron(III) citrate; Ferric citrate", gmoid: "GMO_001118" },
  { name: "Iron(III) citrate solution", gmoid: "GMO_001079" },
  { name: "Iron(III) oxide, poorly crystalline, solution", gmoid: "GMO_001907" },
  { name: "Iron(III) pyrophosphate; Ferric pyrophosphate", gmoid: "GMO_001846" },
  { name: "Iron(III) sulfate; Ferric sulfate", gmoid: "GMO_001211" },
  { name: "Iron(III) sulfate n-hydrate", gmoid: "GMO_001304" },
  { name: "Isobutyric acid; 2-methylpropanoic acid", gmoid: "GMO_001184" },
  { name: "Isoleucine", gmoid: "GMO_001782" },
  { name: "Isovaleric acid; 3-Methylbutanoic acid", gmoid: "GMO_001182" },
  { name: "Kanamycin solution", gmoid: "GMO_001384" },
  { name: "Kanamycin sulfate solution", gmoid: "GMO_001371" },
  { name: "Keratin", gmoid: "GMO_001389" },
  { name: "L-Alanine", gmoid: "GMO_001766" },
  { name: "L-Arginine", gmoid: "GMO_001767" },
  { name: "L-Arginine monohydrochloride", gmoid: "GMO_001887" },
  { name: "L-Ascorbic acid; Vitamin C", gmoid: "GMO_001813" },
  { name: "L-Asparagine", gmoid: "GMO_001870" },
  { name: "L-Asparagine monohydrate", gmoid: "GMO_001888" },
  { name: "L-Aspartic acid", gmoid: "GMO_001770" },
  { name: "L-Cysteine hydrochloride", gmoid: "GMO_001828" },
  { name: "L-Cysteine hydrochloride monohydrate", gmoid: "GMO_001205" },
  { name: "L-Cysteine hydrochloride monohydrate solution", gmoid: "GMO_001496" },
  { name: "L-Cystine", gmoid: "GMO_001331" },
  { name: "L-Cystine dihydrochloride", gmoid: "GMO_001886" },
  { name: "L-Cystine hydrochloride monohydrate", gmoid: "GMO_001569" },
  { name: "L-Glutamic acid", gmoid: "GMO_001570" },
  { name: "L-Glutamic acid sodium salt", gmoid: "GMO_001889" },
  { name: "L-Glutamine", gmoid: "GMO_001776" },
  { name: "L-Histidine", gmoid: "GMO_001872" },
  { name: "L-Histidine monohydrochloride", gmoid: "GMO_001762" },
  { name: "L-Histidine monohydrochloride monohydrate", gmoid: "GMO_001778" },
  { name: "L-Isoleucine", gmoid: "GMO_001783" },
  { name: "L-Leucine", gmoid: "GMO_001785" },
  { name: "L-Lysine", gmoid: "GMO_001788" },
  { name: "L-Lysine monohydrochloride; L-Lysine HCl", gmoid: "GMO_001790" },
  { name: "L-Methionine ", gmoid: "GMO_001791" },
  { name: "L-Phenylalanine ", gmoid: "GMO_001794" },
  { name: "L-Proline", gmoid: "GMO_001797" },
  { name: "L-Serine", gmoid: "GMO_001800" },
  { name: "L-Serine solution", gmoid: "GMO_001899" },
  { name: "L-Threonine", gmoid: "GMO_001803" },
  { name: "L-Tryptophan", gmoid: "GMO_001805" },
  { name: "L-Tyrosine", gmoid: "GMO_001808" },
  { name: "L-Tyrosine disodium salt dihydrate", gmoid: "GMO_001874" },
  { name: "L-Valine", gmoid: "GMO_001811" },
  { name: "LB medium; Lysogeny broth", gmoid: "GMO_001842" },
  { name: "LB medium, Lennox", gmoid: "GMO_001845" },
  { name: "LB medium, Luria", gmoid: "GMO_001844" },
  { name: "LB medium, Miller", gmoid: "GMO_001843" },
  { name: "Lab Lemco", gmoid: "GMO_001217" },
  { name: "Lactose", gmoid: "GMO_001445" },
  { name: "Larchwood xylan (Sigma); Larch wood xylan (Sigma)", gmoid: "GMO_001573" },
  { name: "Leibovitz's L-15 medium", gmoid: "GMO_001741" },
  { name: "Leucine", gmoid: "GMO_001411" },
  { name: "Lipoic acid; Thioctic acid, alpha Lipoic acid", gmoid: "GMO_001699" },
  { name: "Lithium chloride", gmoid: "GMO_001431" },
  { name: "Liver extract", gmoid: "GMO_001830" },
  { name: "Liver extract concentrate (NBCo)", gmoid: "GMO_001742" },
  { name: "Lysine", gmoid: "GMO_001787" },
  { name: "M17 broth (Oxoid)", gmoid: "GMO_001376" },
  { name: "MES; 2-(N-morpholino)ethanesulfonic acid", gmoid: "GMO_001191" },
  { name: "MES solution", gmoid: "GMO_001733" },
  { name: "MJ(-N) synthetic seawater", gmoid: "GMO_001900" },
  { name: "MOPS; 3-(N-morpholino)propanesulfonic acid", gmoid: "GMO_001152" },
  { name: "MOPS solution", gmoid: "GMO_001480" },
  { name: "Magnesium acetate", gmoid: "GMO_001188" },
  { name: "Magnesium chloride", gmoid: "GMO_001154" },
  { name: "Magnesium chloride dihydrate", gmoid: "GMO_001266" },
  { name: "Magnesium chloride heptahydrate", gmoid: "GMO_001586" },
  { name: "Magnesium chloride hexahydrate", gmoid: "GMO_001013" },
  { name: "Magnesium chloride hexahydrate solution", gmoid: "GMO_001286" },
  { name: "Magnesium chloride monohydrate", gmoid: "GMO_001171" },
  { name: "Magnesium chloride monohydrate solution", gmoid: "GMO_001697" },
  { name: "Magnesium chloride pentahydrate", gmoid: "GMO_001585" },
  {
    name: "Magnesium glycerophosphate; DL-alpha-Glycerol phosphate magnesium salt hydrate",
    gmoid: "GMO_001841",
  },
  { name: "Magnesium nitrate", gmoid: "GMO_001884" },
  { name: "Magnesium nitrate hexahydrate", gmoid: "GMO_001584" },
  { name: "Magnesium oxide", gmoid: "GMO_001199" },
  { name: "Magnesium sulfate; Magnesium sulphate", gmoid: "GMO_001096" },
  { name: "Magnesium sulfate anhydrate", gmoid: "GMO_001818" },
  { name: "Magnesium sulfate heptahydrate", gmoid: "GMO_001002" },
  { name: "Magnesium sulfate heptahydrate solution", gmoid: "GMO_001463" },
  { name: "Magnesium sulfate hexahydrate", gmoid: "GMO_001446" },
  { name: "Magnesium sulfate monohydrate", gmoid: "GMO_001587" },
  { name: "Magnesium sulfate solution", gmoid: "GMO_001451" },
  { name: "Malachite green", gmoid: "GMO_001885" },
  { name: "Malachite green solution", gmoid: "GMO_001493" },
  { name: "Malonic acid; Propanedioic acid", gmoid: "GMO_001428" },
  { name: "Malt extract", gmoid: "GMO_001059" },
  { name: "Malt extract agar (Nissui)", gmoid: "GMO_001306" },
  { name: "Malted wheat meal", gmoid: "GMO_001578" },
  { name: "Maltose; Malt sugar, Maltobiose", gmoid: "GMO_001195" },
  { name: "Maltose monohydrate", gmoid: "GMO_001579" },
  { name: "Maltose, technical (Difco)", gmoid: "GMO_001580" },
  { name: "Manganese EDTA; Mn-EDTA", gmoid: "GMO_001839" },
  { name: "Manganese chloride", gmoid: "GMO_001589" },
  { name: "Manganese chloride dihydrate; Manganous chloride dihydrate", gmoid: "GMO_001129" },
  { name: "Manganese chloride hexahydrate", gmoid: "GMO_001591" },
  { name: "Manganese chloride monohydrate", gmoid: "GMO_001592" },
  { name: "Manganese chloride tetrahydrate", gmoid: "GMO_001020" },
  { name: "Manganese sulfate", gmoid: "GMO_001763" },
  { name: "Manganese sulfate dihydrate", gmoid: "GMO_001068" },
  { name: "Manganese sulfate heptahydrate; Manganous sulfate heptahydrate", gmoid: "GMO_001381" },
  { name: "Manganese sulfate monohydrate", gmoid: "GMO_001081" },
  { name: "Manganese sulfate n-hydrate; Manganese sulfate x-hydrate", gmoid: "GMO_001065" },
  { name: "Manganese sulfate pentahydrate", gmoid: "GMO_001150" },
  { name: "Manganese sulfate solution", gmoid: "GMO_001342" },
  { name: "Manganese sulfate tetrahydrate", gmoid: "GMO_001064" },
  { name: "Mannitol", gmoid: "GMO_001135" },
  { name: "MeM alpha modification (BioWest)", gmoid: "GMO_001581" },
  { name: "Meat extract", gmoid: "GMO_001074" },
  { name: "Meat peptone", gmoid: "GMO_001868" },
  { name: "Melibiose", gmoid: "GMO_001582" },
  { name: "Menadione; Vitamin K3", gmoid: "GMO_001908" },
  { name: "Menadione solution", gmoid: "GMO_001909" },
  { name: 'Metals "44"', gmoid: "GMO_001856" },
  { name: "Methanol; Methyl alcohol, Methyl alcohol", gmoid: "GMO_001082" },
  { name: "Methanol solution", gmoid: "GMO_001508" },
  { name: "Methionine", gmoid: "GMO_001378" },
  { name: "Methylamine", gmoid: "GMO_001583" },
  { name: "Methylamine hydrochloride", gmoid: "GMO_001303" },
  { name: "Mevalonic acid", gmoid: "GMO_001368" },
  { name: "Middlebrook 7H10 agar (Difco)", gmoid: "GMO_001588" },
  { name: "Milli-Q water; MilliQ water", gmoid: "GMO_001743" },
  { name: "Molybdenum trioxide", gmoid: "GMO_001252" },
  {
    name: "Monopotassium phosphite; Monobasic potassium phosphate, Potassium dihydrogen phosphate, Potassium;dihydrogen phosphite",
    gmoid: "GMO_001714",
  },
  { name: "Monosodium EDTA", gmoid: "GMO_001161" },
  { name: "Mueller hinton II agar (BBL)", gmoid: "GMO_001595" },
  { name: "Murashige & Skoog's plant salt mixture", gmoid: "GMO_001311" },
  { name: "N-Z-Amine A (Sheffield)", gmoid: "GMO_001140" },
  { name: "N-Z-Case (Wako)", gmoid: "GMO_001597" },
  { name: "N-acetylglucosamine; GlcNAc, N-acetyl-D-glucosamine", gmoid: "GMO_001404" },
  { name: "N-acetylglucosamine (Sigma); GlcNAc, N-acetyl-D-glucosamine", gmoid: "GMO_001708" },
  { name: "Naphthalene", gmoid: "GMO_001307" },
  { name: "Neutral red", gmoid: "GMO_001897" },
  { name: "Neutralized sulfide solution", gmoid: "GMO_001105" },
  { name: "Nickel ammonium sulfate", gmoid: "GMO_001280" },
  {
    name: "Nickel ammonium sulfate hexahydrate; Diammonium nickel disulfate hexahydrate",
    gmoid: "GMO_001102",
  },
  { name: "Nickel chloride", gmoid: "GMO_001611" },
  { name: "Nickel chloride hexahydrate", gmoid: "GMO_001022" },
  { name: "Nickel chloride hexahydrate solution", gmoid: "GMO_001923" },
  { name: "Nickel chloride hydrate", gmoid: "GMO_001612" },
  { name: "Nickel chloride pentahydrate", gmoid: "GMO_001760" },
  { name: "Nickel(II) sulfate heptahydrate", gmoid: "GMO_001613" },
  { name: "Nickel(II) sulfate hexahydrate", gmoid: "GMO_001136" },
  { name: "Nicotinamide; Niacinamide, Nicotinic acid amide", gmoid: "GMO_001162" },
  { name: "Nicotinic acid; Niacin, Vitamin B3", gmoid: "GMO_001038" },
  { name: "Nitrilotriacetic acid; NTA", gmoid: "GMO_001053" },
  { name: "Nitrilotriacetic acid disodium salt solution", gmoid: "GMO_001758" },
  { name: "Nitrilotriacetic acid trisodium salt", gmoid: "GMO_001756" },
  { name: "Nitrilotriacetic acid trisodium salt monohydrate", gmoid: "GMO_001752" },
  { name: "Oatmeal", gmoid: "GMO_001134" },
  { name: "Olive oil", gmoid: "GMO_001218" },
  { name: "Ox bile desiccated", gmoid: "GMO_001421" },
  { name: "Oxgall (Difco)", gmoid: "GMO_001614" },
  { name: "Oxioid Cooked meat medium", gmoid: "GMO_001538" },
  { name: "Oxoid Czapek-dox liquid medium, modified", gmoid: "GMO_001377" },
  { name: "Oxoid Lab-lemco beef extract powder", gmoid: "GMO_001690" },
  { name: "Oxoid Lab-lemco broth", gmoid: "GMO_001420" },
  { name: "Oxoid Malt extract agar", gmoid: "GMO_001577" },
  { name: "Oxoid Mycological peptone", gmoid: "GMO_001851" },
  { name: "Oxoid Nutrient broth", gmoid: "GMO_001176" },
  { name: "Oxoid Peptonized milk", gmoid: "GMO_001313" },
  { name: "Oxoid Tryptone soya broth", gmoid: "GMO_001672" },
  { name: "PIPES; Piperazine-N,N′-bis(2-ethanesulfonic acid)", gmoid: "GMO_001223" },
  { name: "PIPES (Sigma)", gmoid: "GMO_001723" },
  { name: "PIPES solution", gmoid: "GMO_001448" },
  { name: "Pancreatic digest of casein", gmoid: "GMO_001615" },
  { name: "Pantothenic acid; Pantothenate, Vitamin B5", gmoid: "GMO_001616" },
  { name: "Papaic digest of soybean", gmoid: "GMO_001835" },
  { name: "Pectin", gmoid: "GMO_001617" },
  { name: "Penicillin", gmoid: "GMO_001618" },
  { name: "Peptic digest of animal tissue", gmoid: "GMO_001619" },
  { name: "Peptic peptone (USB)", gmoid: "GMO_001413" },
  { name: "Peptone", gmoid: "GMO_000012" },
  { name: "Peptone (Oxoid)", gmoid: "GMO_001620" },
  { name: "Peptone solution", gmoid: "GMO_001734" },
  { name: "Phenanthrene", gmoid: "GMO_001334" },
  { name: "Phenol red; Phenolsulfonphthalein", gmoid: "GMO_001156" },
  { name: "Phenol red sodium salt; Sodium phenol red", gmoid: "GMO_001864" },
  { name: "Phenol red solution; Phenolsulfonphthalein solution", gmoid: "GMO_001460" },
  { name: "Phenol solution", gmoid: "GMO_001728" },
  { name: "Phenylalanine", gmoid: "GMO_001793" },
  { name: "Phosphate buffer", gmoid: "GMO_001916" },
  { name: "Phosphate buffer (pH 7.2)", gmoid: "GMO_001915" },
  { name: "Phthalic acid", gmoid: "GMO_001444" },
  { name: "Plant extract", gmoid: "GMO_001859" },
  { name: "Polyethylene glycol", gmoid: "GMO_001425" },
  { name: "Polypeptone", gmoid: "GMO_001080" },
  { name: "Polysorbate 20; Tween 20", gmoid: "GMO_001675" },
  { name: "Polysorbate 60; Tween 60", gmoid: "GMO_001386" },
  { name: "Polysorbate 80; Tween 80", gmoid: "GMO_001060" },
  { name: "Potassium acetate", gmoid: "GMO_001724" },
  { name: "Potassium bicarbonate", gmoid: "GMO_001317" },
  { name: "Potassium bromide", gmoid: "GMO_001108" },
  { name: "Potassium chloride", gmoid: "GMO_001017" },
  { name: "Potassium hydroxide", gmoid: "GMO_001902" },
  { name: "Potassium hydroxide solution", gmoid: "GMO_001903" },
  { name: "Potassium iodide", gmoid: "GMO_001091" },
  { name: "Potassium nitrate", gmoid: "GMO_001056" },
  { name: "Potassium nitrate solution", gmoid: "GMO_001469" },
  { name: "Potassium phosphate buffer", gmoid: "GMO_001308" },
  {
    name: "Potassium phosphate dibasic; Dipotassium hydrogen phosphate, Dipotassium phosphate",
    gmoid: "GMO_001009",
  },
  { name: "Potassium phosphate dibasic solution", gmoid: "GMO_001467" },
  {
    name: "Potassium phosphate dibasic trihydrate; Dipotassium phosphate trihydrate",
    gmoid: "GMO_001125",
  },
  { name: "Potassium phosphate monobasic; Monopotassium phosphate", gmoid: "GMO_001006" },
  {
    name: "Potassium phosphate monobasic dihydrate; Monopotassium phosphate dihydrate",
    gmoid: "GMO_001568",
  },
  { name: "Potassium phosphate monobasic solution", gmoid: "GMO_001468" },
  { name: "Potassium sulfate", gmoid: "GMO_001173" },
  { name: "Potassium sulfate heptahydrate", gmoid: "GMO_001567" },
  { name: "Potassium tetrathionate", gmoid: "GMO_001566" },
  { name: "Potassium tetrathionate solution", gmoid: "GMO_001450" },
  { name: "Potassium thiocyanate", gmoid: "GMO_001241" },
  { name: "Potassium thiocyanate solution", gmoid: "GMO_001492" },
  { name: "Potato", gmoid: "GMO_001092" },
  { name: "Potato dextrose agar (Nissui)", gmoid: "GMO_001374" },
  { name: "Prepared culture medium", gmoid: "GMO_000019" },
  { name: "Press yeast", gmoid: "GMO_001174" },
  { name: "Probumin universal grade (Merck Millipore)", gmoid: "GMO_001625" },
  { name: "Proline", gmoid: "GMO_001796" },
  { name: "Propionic acid; Propionic acid", gmoid: "GMO_001192" },
  { name: "Proteose peptone", gmoid: "GMO_001185" },
  { name: "Pullulan", gmoid: "GMO_001725" },
  { name: "Purified agar", gmoid: "GMO_001423" },
  { name: "Purified water", gmoid: "GMO_001890" },
  { name: "Putrescine", gmoid: "GMO_001628" },
  { name: "Pyridoxal hydrochloride", gmoid: "GMO_001167" },
  { name: "Pyridoxal phosphate; PLP", gmoid: "GMO_001629" },
  { name: "Pyridoxamine; Vitamin B6", gmoid: "GMO_001751" },
  { name: "Pyridoxamine dihydrochloride", gmoid: "GMO_001630" },
  { name: "Pyridoxamine hydrochloride", gmoid: "GMO_001631" },
  { name: "Pyridoxine; Vitamin B6", gmoid: "GMO_001632" },
  { name: "Pyridoxine dihydrochloride", gmoid: "GMO_001253" },
  { name: "Pyridoxine hydrochloride", gmoid: "GMO_001029" },
  { name: "Pyruvate solution", gmoid: "GMO_001263" },
  { name: "Quinic acid", gmoid: "GMO_001248" },
  { name: "Quinic acid solution", gmoid: "GMO_001740" },
  { name: "R2A agar (Difco)", gmoid: "GMO_001633" },
  { name: "R2A broth DAIGO (Nihon seiyaku)", gmoid: "GMO_001213" },
  { name: "Rabbit blood", gmoid: "GMO_001634" },
  { name: "Rabbit serum", gmoid: "GMO_001635" },
  { name: "Raffinose", gmoid: "GMO_001210" },
  { name: "Reinforced clostridial agar (Sigma)", gmoid: "GMO_001636" },
  { name: "Reinforced clostridial medium (Difco)", gmoid: "GMO_001637" },
  { name: "Reinforced clostridial medium (Oxoid)", gmoid: "GMO_001242" },
  { name: "Resazurin; 7-Hydroxy-3H-phenoxazin-3-one 10-oxide", gmoid: "GMO_001012" },
  { name: "Resazurin solution", gmoid: "GMO_001403" },
  { name: "Rhamnose", gmoid: "GMO_001272" },
  { name: "Riboflavin; Vitamin B2", gmoid: "GMO_001037" },
  { name: "Riboflavin 5'-monophosphate sodium salt dihydrate", gmoid: "GMO_001875" },
  { name: "Ribose", gmoid: "GMO_001638" },
  { name: "Rifampicin solution", gmoid: "GMO_001164" },
  { name: "Rumen fluid", gmoid: "GMO_001727" },
  { name: "Rumen fluid (clarified)", gmoid: "GMO_001534" },
  { name: "Rye-bran", gmoid: "GMO_001639" },
  { name: "Rye-bran extract", gmoid: "GMO_001640" },
  { name: "SOB medium; Super Optimal Broth", gmoid: "GMO_001966" },
  { name: "Sake", gmoid: "GMO_001641" },
  { name: "Se-W solution", gmoid: "GMO_001857" },
  { name: "Se/W solution", gmoid: "GMO_001121" },
  { name: "Sea salts (SIGMA)", gmoid: "GMO_001231" },
  { name: "Sea water filtered", gmoid: "GMO_001447" },
  { name: "Seawater", gmoid: "GMO_001066" },
  { name: "Selenium salt", gmoid: "GMO_001642" },
  { name: "Selenous acid; Selenious acid", gmoid: "GMO_001717" },
  { name: "Serine", gmoid: "GMO_001799" },
  { name: "Serum-derived component", gmoid: "GMO_001879" },
  { name: "Sheep blood, defibrinated", gmoid: "GMO_001506" },
  { name: "Silicone based defoamers", gmoid: "GMO_001840" },
  { name: "Skim milk", gmoid: "GMO_001172" },
  { name: "Skim milk (Difco)", gmoid: "GMO_001643" },
  { name: "Sludge fluid", gmoid: "GMO_001296" },
  { name: "Sodium DL-lactate", gmoid: "GMO_001644" },
  { name: "Sodium DL-malate", gmoid: "GMO_001645" },
  { name: "Sodium L-lactate", gmoid: "GMO_001362" },
  { name: "Sodium L-malate", gmoid: "GMO_001646" },
  { name: "Sodium acetate; NaOAc, Sodium ethanoate", gmoid: "GMO_001031" },
  { name: "Sodium acetate solution", gmoid: "GMO_001415" },
  { name: "Sodium acetate trihydrate", gmoid: "GMO_001396" },
  { name: "Sodium alginate", gmoid: "GMO_001443" },
  { name: "Sodium ampicillin solution", gmoid: "GMO_001436" },
  { name: "Sodium ascorbate", gmoid: "GMO_001225" },
  { name: "Sodium ascorbate solution", gmoid: "GMO_001478" },
  { name: "Sodium aspartate", gmoid: "GMO_001330" },
  { name: "Sodium benzoate", gmoid: "GMO_001336" },
  { name: "Sodium benzoate solution", gmoid: "GMO_001509" },
  { name: "Sodium bicarbonate; Sodium hydrogen carbonate", gmoid: "GMO_001019" },
  { name: "Sodium bicarbonate (Sigma)", gmoid: "GMO_001607" },
  { name: "Sodium bicarbonate solution", gmoid: "GMO_001119" },
  { name: "Sodium bisulfite", gmoid: "GMO_001608" },
  { name: "Sodium bromide", gmoid: "GMO_001073" },
  { name: "Sodium butyrate", gmoid: "GMO_001648" },
  { name: "Sodium butyrate solution", gmoid: "GMO_001473" },
  { name: "Sodium carbonate", gmoid: "GMO_001045" },
  { name: "Sodium carbonate solution", gmoid: "GMO_001216" },
  { name: "Sodium carbonate-Carbon dioxide buffer", gmoid: "GMO_001503" },
  { name: "Sodium chlorate", gmoid: "GMO_001722" },
  { name: "Sodium chloride", gmoid: "GMO_001004" },
  { name: "Sodium chloride solution", gmoid: "GMO_001355" },
  { name: "Sodium citrate", gmoid: "GMO_001109" },
  { name: "Sodium citrate dihydrate", gmoid: "GMO_001753" },
  { name: "Sodium citrate solution", gmoid: "GMO_001321" },
  {
    name: "Sodium dihydrogen phosphate; Anhydrous monobasic sodium phosphate, Monosodium phosphate, Sodium phosphate monobasic anhydrous",
    gmoid: "GMO_001352",
  },
  {
    name: "Sodium dihydrogen phosphate dihydrate; Anhydrous monobasic sodium phosphate dihydrate, Monosodium phosphate dihydrate",
    gmoid: "GMO_001605",
  },
  {
    name: "Sodium dihydrogen phosphate monohydrate; Anhydrous monobasic sodium phosphate monohydrate, Monosodium phosphate monohydrate",
    gmoid: "GMO_001606",
  },
  { name: "Sodium dithionite", gmoid: "GMO_001354" },
  { name: "Sodium dithionite dihydrate", gmoid: "GMO_001720" },
  { name: "Sodium dithionite solution", gmoid: "GMO_001721" },
  { name: "Sodium fluoride", gmoid: "GMO_001107" },
  {
    name: "Sodium formaldehyde sulfoxylate; Rongalite, Sodium hydroxymethylsulfinate, Sodium oxymethylene sulfoxylate",
    gmoid: "GMO_001836",
  },
  { name: "Sodium formate", gmoid: "GMO_001120" },
  { name: "Sodium formate solution", gmoid: "GMO_001491" },
  { name: "Sodium fumarate solution", gmoid: "GMO_001474" },
  { name: "Sodium gluconate", gmoid: "GMO_001649" },
  { name: "Sodium glutamate; MSG, Monosodium glutamate", gmoid: "GMO_001094" },
  { name: "Sodium glutamate monohydrate; Monosodium glutamate monohydrate", gmoid: "GMO_001168" },
  { name: "Sodium glycerophosphate; Disodium beta-Glycerophosphate", gmoid: "GMO_001405" },
  { name: "Sodium hydroxide", gmoid: "GMO_001078" },
  { name: "Sodium hydroxide solution", gmoid: "GMO_001300" },
  { name: "Sodium hygromycin solution", gmoid: "GMO_001325" },
  { name: "Sodium lactate", gmoid: "GMO_001090" },
  { name: "Sodium lactate solution", gmoid: "GMO_001363" },
  { name: "Sodium malate", gmoid: "GMO_001143" },
  { name: "Sodium metasilicate", gmoid: "GMO_001341" },
  { name: "Sodium metasilicate nonahydrate", gmoid: "GMO_001604" },
  { name: "Sodium metavanadate monohydrate", gmoid: "GMO_001609" },
  { name: "Sodium molybdate", gmoid: "GMO_001719" },
  { name: "Sodium molybdate dihydrate", gmoid: "GMO_001011" },
  { name: "Sodium molybdate dihydrate solution", gmoid: "GMO_001718" },
  { name: "Sodium molybdate solution", gmoid: "GMO_001380" },
  { name: "Sodium n-hexanoate", gmoid: "GMO_001256" },
  { name: "Sodium nitrate", gmoid: "GMO_001049" },
  { name: "Sodium nitrate solution", gmoid: "GMO_001472" },
  { name: "Sodium nitrite", gmoid: "GMO_001329" },
  { name: "Sodium oleate", gmoid: "GMO_001650" },
  { name: "Sodium palmitate", gmoid: "GMO_001651" },
  { name: "Sodium phosphate buffer", gmoid: "GMO_001124" },
  { name: "Sodium propionate", gmoid: "GMO_001288" },
  { name: "Sodium pyruvate; Pyruvic acid sodium salt", gmoid: "GMO_001055" },
  { name: "Sodium pyruvate solution; Pyruvic acid sodium salt solution", gmoid: "GMO_001475" },
  { name: "Sodium resazurin solution", gmoid: "GMO_001453" },
  { name: "Sodium selenate", gmoid: "GMO_001602" },
  { name: "Sodium selenate pentahydrate", gmoid: "GMO_001603" },
  { name: "Sodium selenate soution", gmoid: "GMO_001477" },
  { name: "Sodium selenite", gmoid: "GMO_001093" },
  { name: "Sodium selenite pentahydrate", gmoid: "GMO_001046" },
  { name: "Sodium silicate", gmoid: "GMO_001236" },
  { name: "Sodium silicate nonahydrate", gmoid: "GMO_001198" },
  { name: "Sodium succinate", gmoid: "GMO_001070" },
  { name: "Sodium succinate solution", gmoid: "GMO_001462" },
  { name: "Sodium sulfate", gmoid: "GMO_001052" },
  { name: "Sodium sulfide", gmoid: "GMO_001323" },
  { name: "Sodium sulfide nonahydrate", gmoid: "GMO_001014" },
  { name: "Sodium sulfide nonahydrate solution", gmoid: "GMO_001494" },
  { name: "Sodium sulfide solution", gmoid: "GMO_001315" },
  { name: "Sodium sulfite solution", gmoid: "GMO_001452" },
  { name: "Sodium tartrate", gmoid: "GMO_001200" },
  { name: "Sodium terephthalate", gmoid: "GMO_001283" },
  { name: "Sodium tetrathionate", gmoid: "GMO_001349" },
  { name: "Sodium thioglycolate; Sodium thioglycollate", gmoid: "GMO_001132" },
  { name: "Sodium thiosulfate", gmoid: "GMO_001098" },
  { name: "Sodium thiosulfate pentahydrate", gmoid: "GMO_001041" },
  { name: "Sodium thiosulfate pentahydrate solution", gmoid: "GMO_001486" },
  { name: "Sodium thiosulfate solution", gmoid: "GMO_001471" },
  { name: "Sodium tungstate", gmoid: "GMO_001086" },
  { name: "Sodium tungstate dihydrate", gmoid: "GMO_001057" },
  { name: "Sodium tungstate monohydrate", gmoid: "GMO_001186" },
  { name: "Soil extract", gmoid: "GMO_001166" },
  { name: "Soluble starch", gmoid: "GMO_001837" },
  { name: "Soluble starch (Difco)", gmoid: "GMO_001653" },
  { name: "Soluble starch (Sigma)", gmoid: "GMO_001654" },
  { name: "Sorbitan monooleate", gmoid: "GMO_001207" },
  { name: "Sorbitol", gmoid: "GMO_001369" },
  { name: "Soy protein isolate", gmoid: "GMO_001346" },
  { name: "Soybean peptone; Soy peptone, Soya peptone", gmoid: "GMO_001251" },
  { name: "Starch", gmoid: "GMO_001054" },
  { name: "Starch from corn (SIGMA); Cornstarch", gmoid: "GMO_001339" },
  { name: "Sterile horse serum", gmoid: "GMO_001655" },
  { name: "Streptomycin sulfate", gmoid: "GMO_001713" },
  { name: "Strontium chloride", gmoid: "GMO_001153" },
  { name: "Strontium chloride hexahydrate", gmoid: "GMO_001085" },
  { name: "Succinic acid", gmoid: "GMO_001656" },
  { name: "Sucrose", gmoid: "GMO_001067" },
  { name: "Sugar solution (JCM 537)", gmoid: "GMO_001928" },
  { name: "Sulfur powder", gmoid: "GMO_001062" },
  { name: "Sulfuric acid solution; Sulphuric acid", gmoid: "GMO_001482" },
  { name: "TAPS", gmoid: "GMO_001372" },
  {
    name: "TAPSO; N-[Tris(hydroxymethyl)methyl]-3-amino-2-hydroxypropanesulfonic acid",
    gmoid: "GMO_001418",
  },
  { name: "TES", gmoid: "GMO_001712" },
  { name: "Tap water", gmoid: "GMO_001131" },
  { name: "Tetramethyl ammonium", gmoid: "GMO_001659" },
  { name: "Thiamin solution", gmoid: "GMO_001367" },
  { name: "Thiamine; Vitamin B1", gmoid: "GMO_001230" },
  { name: "Thiamine hydrochloride", gmoid: "GMO_001027" },
  { name: "Thiamine hydrochloride dihydrate", gmoid: "GMO_001278" },
  { name: "Thiamine monophosphate", gmoid: "GMO_001877" },
  { name: "Thiamine monophosphate chloride dihydrate", gmoid: "GMO_001878" },
  { name: "Thiamine pyrophosphate; Cocarboxylase, TPP", gmoid: "GMO_001660" },
  { name: "Thiamine pyrophosphate solution", gmoid: "GMO_001457" },
  { name: "Thioglycolate medium", gmoid: "GMO_001838" },
  { name: "Thioglycolate medium dehydrated", gmoid: "GMO_001220" },
  { name: "Thioglycolate medium dehydrated (Wako)", gmoid: "GMO_001227" },
  { name: "Thioglycolic acid; Mercaptoacetic acid", gmoid: "GMO_001356" },
  { name: "Thioglycolic acid solution; Mercaptoacetic acid solution", gmoid: "GMO_001319" },
  { name: "Thioglycollate medium (Sigma)", gmoid: "GMO_001662" },
  { name: "Thiosulfate", gmoid: "GMO_001927" },
  { name: "Threonine", gmoid: "GMO_001802" },
  { name: "Thymidine", gmoid: "GMO_001820" },
  { name: "Thymine", gmoid: "GMO_001271" },
  { name: "Tin(II) chloride dihydrate", gmoid: "GMO_001338" },
  { name: "Titanium(III) chloride; Titanium chloride", gmoid: "GMO_001711" },
  { name: "Titanium(III) chloride solution", gmoid: "GMO_001387" },
  { name: "Toluene", gmoid: "GMO_001663" },
  { name: "Toluene solution", gmoid: "GMO_001507" },
  { name: "Tomato", gmoid: "GMO_001244" },
  { name: "Toray silicone SH 5535 solution", gmoid: "GMO_001487" },
  { name: "Trace element solution (JCM 480)", gmoid: "GMO_001913" },
  { name: "Trace metal element SL-10", gmoid: "GMO_001855" },
  { name: "Trace metal element SL-6", gmoid: "GMO_001852" },
  { name: "Trace metal element SL-7", gmoid: "GMO_001853" },
  { name: "Trace metal element SL-8", gmoid: "GMO_001854" },
  { name: "Trace mineral solution (JCM 151)", gmoid: "GMO_001905" },
  { name: "Trace mineral solution (JCM 369)", gmoid: "GMO_001906" },
  { name: "Trace mineral solution (JCM 411)", gmoid: "GMO_001904" },
  { name: "Trehalose; Mycose, Tremalose", gmoid: "GMO_001234" },
  { name: "Trichloroethylene", gmoid: "GMO_001710" },
  { name: "Triethanolamine", gmoid: "GMO_001664" },
  { name: "Trimethylamine hydrochloride", gmoid: "GMO_001126" },
  { name: "Trimethylamine hydrochloride solution", gmoid: "GMO_001739" },
  {
    name: "Tris; THAM, Tris base, Tris hydrochloride, Tris(hydroxymethyl)aminomethane",
    gmoid: "GMO_001233",
  },
  { name: "Tris buffer; Tris hydrochloride buffer", gmoid: "GMO_001730" },
  { name: "Trisodium EDTA", gmoid: "GMO_001158" },
  { name: "Trisodium citrate", gmoid: "GMO_001160" },
  { name: "Trisodium citrate dihydrate", gmoid: "GMO_001249" },
  { name: "Trisodium citrate monohydrate", gmoid: "GMO_001665" },
  { name: "Trypsin (Sigma-Aldrich)", gmoid: "GMO_001666" },
  { name: "Trypticase", gmoid: "GMO_001276" },
  { name: "Trypticase soy", gmoid: "GMO_001408" },
  { name: "Trypticase soy agar (BBL)", gmoid: "GMO_001669" },
  { name: "Trypto-soya agar (Nissui)", gmoid: "GMO_001671" },
  { name: "Tryptophan", gmoid: "GMO_001215" },
  { name: "Tungstic acid", gmoid: "GMO_001560" },
  { name: "Turbo cornutus meat cut", gmoid: "GMO_001269" },
  { name: "Tyrosine", gmoid: "GMO_001807" },
  { name: "Ultrapure water", gmoid: "GMO_001892" },
  { name: "Uracil", gmoid: "GMO_001676" },
  { name: "Urea", gmoid: "GMO_001133" },
  { name: "Uric acid", gmoid: "GMO_001335" },
  { name: "Uridine-5-Triphosphate monosodium salt", gmoid: "GMO_001866" },
  { name: "V-8 Juice", gmoid: "GMO_001290" },
  { name: "Valeric acid; Pentanoic acid", gmoid: "GMO_001181" },
  { name: "Valine", gmoid: "GMO_001810" },
  { name: "Vanadyl sulfate", gmoid: "GMO_001894" },
  { name: "Vanadyl sulfate dihydrate", gmoid: "GMO_001332" },
  { name: "Vanadyl sulfate n-hydrate", gmoid: "GMO_001151" },
  { name: "Vanadyl sulfate n-hydrate solution ", gmoid: "GMO_001678" },
  { name: "Vanadyl sulfate pentahydrate", gmoid: "GMO_001677" },
  { name: "Vancomycin hydrochloride solution", gmoid: "GMO_001679" },
  { name: "Vegetable juice", gmoid: "GMO_001400" },
  { name: "Vitamin K1", gmoid: "GMO_001829" },
  { name: "Vitamin K1 solution", gmoid: "GMO_001419" },
  { name: "Volvic water", gmoid: "GMO_001441" },
  { name: "Water", gmoid: "GMO_001891" },
  { name: "Whole egg", gmoid: "GMO_001680" },
  { name: "Wine", gmoid: "GMO_001416" },
  { name: "Wolfe's mineral solution", gmoid: "GMO_001910" },
  { name: "Wolfe's mineral solution, modified (JCM 915)", gmoid: "GMO_001911" },
  { name: "Xylan", gmoid: "GMO_001401" },
  { name: "Xylose", gmoid: "GMO_001239" },
  { name: "Yeast", gmoid: "GMO_001898" },
  { name: "Yeast autolysate", gmoid: "GMO_001683" },
  { name: "Yeast cell paste", gmoid: "GMO_001914" },
  { name: "Yeast extract", gmoid: "GMO_001003" },
  { name: "Yeast extract solution", gmoid: "GMO_001292" },
  { name: "Yeast extract solution (Gibco 360-8180)", gmoid: "GMO_001501" },
  { name: "Yeast nitrogen base (Difco)", gmoid: "GMO_001686" },
  { name: "Zinc chloride", gmoid: "GMO_001035" },
  { name: "Zinc chloride dihydrate", gmoid: "GMO_001265" },
  { name: "Zinc sulfate", gmoid: "GMO_001764" },
  { name: "Zinc sulfate dihydrate", gmoid: "GMO_001688" },
  { name: "Zinc sulfate heptahydrate", gmoid: "GMO_001023" },
  { name: "Zinc sulfate heptahydrate solution", gmoid: "GMO_001360" },
  { name: "Zinc sulfate monohydrate", gmoid: "GMO_001689" },
  { name: "Zinc sulfate solution", gmoid: "GMO_001277" },
  { name: "alpha-Ketoglutaric acid", gmoid: "GMO_001861" },
  { name: "alpha-Methylbutyric acid; 2-methylbutyric acid", gmoid: "GMO_001299" },
  { name: "cis-4-Hydroxy-L-proline", gmoid: "GMO_001781" },
  { name: "myo-Inositol", gmoid: "GMO_001814" },
  { name: "n-Butanol; n-butyl alcohol, normal butanol", gmoid: "GMO_001258" },
  { name: "trans-4-Hydroxy-L-proline", gmoid: "GMO_001780" },
  { name: "Rabbit serum sterile non-hemolyzed (Pel-Freez, code No. 31125)", gmoid: "GMO_001726" },
  {
    name: "Bacto yeast nitrogen base without amino acids and ammonium sulfate",
    gmoid: "GMO_001382",
  },
  { name: "Gibco Horse Serum, heat inactivated, New Zealand origin", gmoid: "GMO_001960" },
];
