import { AllComponentsResponse } from "./types";

export const allComponentsResponse: AllComponentsResponse = [
  {
    name: "Hexahydro-1H-1,4-diazepine-1,4-bis(2-ethanesulfonic acid) solution; HomoPIPES solution, HomoPIPES solution",
    gmo_id: "GMO_001925",
  },
  { name: "Disodium phosphate-Potassium phosphate monobasic buffer", gmo_id: "GMO_001470" },
  { name: "1,1,2-Trichloroethane; Beta-trichloroethane", gmo_id: "GMO_001731" },
  { name: "1,2-Dichloropropane", gmo_id: "GMO_001732" },
  { name: "1,2-Dichloropropane methanol solution", gmo_id: "GMO_001757" },
  { name: "10xCMD stock solution", gmo_id: "GMO_001917" },
  { name: "2,3-Butanediol", gmo_id: "GMO_001240" },
  { name: "2-Mercaptoethanol", gmo_id: "GMO_001701" },
  { name: "2-Methylbutanoic acid", gmo_id: "GMO_001495" },
  { name: "3-Chloro-4-hydroxyphenylacetic acid", gmo_id: "GMO_001945" },
  { name: "4-Aminobenzoic acid; PABA, para-aminobenzoic acid", gmo_id: "GMO_001026" },
  { name: "5-Methyl-2'-deoxycytidine; 5-Methyldeoxycytidine", gmo_id: "GMO_001863" },
  { name: "ABCM agar (Eiken)", gmo_id: "GMO_001348" },
  { name: "ACES; ACES buffer, N-(2-Acetamido)-2-aminoethanesulfonic acid", gmo_id: "GMO_001860" },
  { name: "Acetate", gmo_id: "GMO_001926" },
  { name: "Acetic acid", gmo_id: "GMO_001179" },
  { name: "Acetoin; 3-hydroxybutanone, Acetyl methyl carbinol", gmo_id: "GMO_001391" },
  { name: "Acid hydrolysates of casein", gmo_id: "GMO_001867" },
  { name: "Activated carbon", gmo_id: "GMO_001289" },
  { name: "Adenine sulfate", gmo_id: "GMO_001398" },
  { name: "Agar", gmo_id: "GMO_001007" },
  { name: "Aged seawater", gmo_id: "GMO_001744" },
  { name: "Alanine", gmo_id: "GMO_001765" },
  { name: "Allantoin; 5-Ureidohydantoin, Glyoxyldiureide", gmo_id: "GMO_001375" },
  { name: "Aluminum chloride", gmo_id: "GMO_001255" },
  { name: "Aluminum chloride hexahydrate", gmo_id: "GMO_001511" },
  { name: "Aluminum potassium sulfate", gmo_id: "GMO_001088" },
  { name: "Aluminum potassium sulfate dodecahydrate", gmo_id: "GMO_001051" },
  { name: "Aluminum potassium sulfate dodecahydrate solution", gmo_id: "GMO_001504" },
  { name: "Ammonium acetate", gmo_id: "GMO_001141" },
  { name: "Ammonium bicarbonate", gmo_id: "GMO_001281" },
  { name: "Ammonium bicarbonate solution", gmo_id: "GMO_001458" },
  { name: "Ammonium chloride", gmo_id: "GMO_001008" },
  { name: "Ammonium chloride solution", gmo_id: "GMO_001394" },
  { name: "Ammonium citrate", gmo_id: "GMO_001208" },
  { name: "Ammonium dihydrogen phosphate", gmo_id: "GMO_001214" },
  { name: "Ammonium ferric citrate", gmo_id: "GMO_001147" },
  { name: "Ammonium ferric citrate solution", gmo_id: "GMO_001454" },
  { name: "Ammonium hydrogen phosphate; DAP, Diammonium phosphate", gmo_id: "GMO_001379" },
  {
    name: "Ammonium iron(II) sulfate; Ferrous ammonium sulfate, Iron(II) ammonium sulfate",
    gmo_id: "GMO_001869",
  },
  { name: "Ammonium iron(II) sulfate heptahydrate", gmo_id: "GMO_001128" },
  {
    name: "Ammonium iron(II) sulfate hexahydrate; Ferrous ammonium sulfate hexahydrate, Iron(II) ammonium sulfate hexahydrate",
    gmo_id: "GMO_001076",
  },
  { name: "Ammonium iron(II) sulfate hexahydrate solution", gmo_id: "GMO_001455" },
  { name: "Ammonium iron(II) sulfate solution", gmo_id: "GMO_001698" },
  { name: "Ammonium nitrate", gmo_id: "GMO_001100" },
  { name: "Ammonium sulfate", gmo_id: "GMO_001030" },
  { name: "Ammonium sulfate heptahydrate", gmo_id: "GMO_001209" },
  { name: "Ammonium tartrate", gmo_id: "GMO_001361" },
  { name: "Ampicillin solution", gmo_id: "GMO_001512" },
  { name: "Anaerobic water", gmo_id: "GMO_001513" },
  { name: "Arabinose", gmo_id: "GMO_001350" },
  { name: "Arginine", gmo_id: "GMO_001203" },
  { name: "Artificial seawater", gmo_id: "GMO_001235" },
  { name: "Artificial seawater with gravimetric salts", gmo_id: "GMO_001880" },
  { name: "Artificial seawater with volumetric salts", gmo_id: "GMO_001881" },
  { name: "Ascorbic acid", gmo_id: "GMO_001247" },
  { name: "Ascorbic acid solution", gmo_id: "GMO_001500" },
  { name: "Asparagine", gmo_id: "GMO_001190" },
  { name: "Aspartic acid", gmo_id: "GMO_001769" },
  { name: "Autolyzed Yeast Extract (15% solution)", gmo_id: "GMO_001314" },
  { name: "BBL BCYE agar base", gmo_id: "GMO_001514" },
  { name: "BBL Brucella agar", gmo_id: "GMO_001522" },
  { name: "BBL Corn meal agar", gmo_id: "GMO_001539" },
  { name: "BBL Fluid thioglycollate medium", gmo_id: "GMO_001555" },
  { name: "BBL Phytone peptone", gmo_id: "GMO_001622" },
  { name: "BBL Polypeptone peptone", gmo_id: "GMO_001424" },
  { name: "BBL Trypticase peptone; BBL &trade; Trypticase &trade; peptone", gmo_id: "GMO_001097" },
  { name: "BBL Trypticase peptone solution", gmo_id: "GMO_001735" },
  { name: "BBL Trypticase soy broth", gmo_id: "GMO_001438" },
  { name: "BCYE agar; Buffered charcoal yeast extract agar", gmo_id: "GMO_001847" },
  { name: "BL agar (Nissui); Glucose blood liver agar", gmo_id: "GMO_001320" },
  { name: "Bacteriological peptone", gmo_id: "GMO_001399" },
  { name: "Bacto &trade; TC yeastolate", gmo_id: "GMO_001657" },
  { name: "Bacto Casamino acids (Difco)", gmo_id: "GMO_001705" },
  { name: "Bacto Neopeptone", gmo_id: "GMO_001610" },
  { name: "Bacto Proteose peptone", gmo_id: "GMO_001626" },
  { name: "Bacto Proteose peptone No. 3", gmo_id: "GMO_001144" },
  { name: "Bacto Soytone", gmo_id: "GMO_001197" },
  { name: "Bacto Tryptic soy broth", gmo_id: "GMO_001117" },
  { name: "Bacto Tryptic soy broth without dextrose", gmo_id: "GMO_001287" },
  { name: "Bacto Tryptone; Tryptone, Bacto &trade;", gmo_id: "GMO_001043" },
  { name: "Bacto Tryptose", gmo_id: "GMO_001673" },
  { name: "Bacto Tryptose phosphate broth (Difco)", gmo_id: "GMO_001674" },
  {
    name: "Bacto Yeast extract; Bacto &trade; Yeast extract, Yeast Extract, Bacto &trade;",
    gmo_id: "GMO_001018",
  },
  { name: "Bacto Yeast extract solution", gmo_id: "GMO_001736" },
  { name: "Bacto agar", gmo_id: "GMO_001130" },
  { name: "Bacto blood agar base", gmo_id: "GMO_001297" },
  { name: "Bacto brain heart infusion; Bacto &trade; brain heart infusion", gmo_id: "GMO_001149" },
  { name: "Bacto casitone; Casitone", gmo_id: "GMO_001104" },
  { name: "Bacto heart infusion broth", gmo_id: "GMO_001146" },
  { name: "Bacto malt extract", gmo_id: "GMO_001159" },
  { name: "Bacto peptone", gmo_id: "GMO_001089" },
  { name: "Bacto todd hewitt broth", gmo_id: "GMO_001254" },
  { name: "Bacto tryptone solution", gmo_id: "GMO_001737" },
  { name: "Bacto yeast nitrogen base without amino acids", gmo_id: "GMO_001194" },
  { name: "Baker's yeast", gmo_id: "GMO_001427" },
  { name: "Barium chloride", gmo_id: "GMO_001515" },
  { name: "Barium chloride dihydrate", gmo_id: "GMO_001516" },
  { name: "Beef brain powder", gmo_id: "GMO_001518" },
  { name: "Beef extract", gmo_id: "GMO_001072" },
  { name: "Beef extract (BD)", gmo_id: "GMO_001442" },
  { name: "Benzene solution", gmo_id: "GMO_001497" },
  { name: "Beta-NAD; NAD, NAD+, Nicotinamide adenine dinucleotide", gmo_id: "GMO_001691" },
  {
    name: "Beta-NADP sodium salt; Beta-NADP-Na, β-Nicotinamide adenine dinucleotide phosphate sodium salt, Beta-Nicotinamide adenine dinucleotide phosphate sodium salt",
    gmo_id: "GMO_001817",
  },
  { name: "Betaine", gmo_id: "GMO_001748" },
  { name: "Betaine solution", gmo_id: "GMO_001479" },
  { name: "Biotin; Coenzyme R, Vitamin B7, Vitamin H", gmo_id: "GMO_001025" },
  { name: "Biphenyl", gmo_id: "GMO_001383" },
  {
    name: "Bis-tris propane; 1,3-bis(tris(hydroxymethyl)methylamino)propane",
    gmo_id: "GMO_001219",
  },
  { name: "Blood-derived component", gmo_id: "GMO_001893" },
  { name: "Bonito extract", gmo_id: "GMO_001246" },
  {
    name: "Borax; Borax decahydrate, Disodium tetraborate decahydrate, Sodium borate decahydrate, Sodium tetraborate decahydrate",
    gmo_id: "GMO_001598",
  },
  { name: "Boric acid", gmo_id: "GMO_001015" },
  {
    name: "Bovine serum albumin; BSA, Bovine serum albumin fraction V, Fraction V",
    gmo_id: "GMO_001520",
  },
  { name: "Bovine serum albumin fraction V (Roche)", gmo_id: "GMO_001333" },
  { name: "Bovine serum albumin fraction V (Wako) ", gmo_id: "GMO_001702" },
  { name: "Brewer anaerobic agar (Difco)", gmo_id: "GMO_001521" },
  { name: "Bromophenol blue", gmo_id: "GMO_001351" },
  { name: "Bromophenol blue solution", gmo_id: "GMO_001901" },
  { name: "Brown rice flakes", gmo_id: "GMO_001345" },
  { name: "Butyric acid; Butanoic acid", gmo_id: "GMO_001178" },
  { name: "CAPSO; 3-(cyclohexylamino)-2-hydroxy-1-propanesulfonic acid", gmo_id: "GMO_001704" },
  { name: "CMRL 1066; Connaugh Medical Research Laboratories 1066 medium", gmo_id: "GMO_001849" },
  { name: "CMRL 1066 (Gibco 330-1540)", gmo_id: "GMO_001523" },
  { name: "CMRL 1066 with glutamate (Sigma)", gmo_id: "GMO_001524" },
  { name: "Calcium carbonate", gmo_id: "GMO_001063" },
  { name: "Calcium chloride", gmo_id: "GMO_001061" },
  { name: "Calcium chloride anhydrate", gmo_id: "GMO_001819" },
  { name: "Calcium chloride dihydrate", gmo_id: "GMO_001005" },
  { name: "Calcium chloride dihydrate solution", gmo_id: "GMO_001228" },
  { name: "Calcium chloride hexahydrate", gmo_id: "GMO_001163" },
  { name: "Calcium chloride hexahydrate solution", gmo_id: "GMO_001459" },
  { name: "Calcium chloride monohydrate", gmo_id: "GMO_001232" },
  { name: "Calcium chloride solution", gmo_id: "GMO_001357" },
  { name: "Calcium folinate; Calcium folinic acid, Leucovorin", gmo_id: "GMO_001526" },
  { name: "Calcium lactate", gmo_id: "GMO_001305" },
  { name: "Calcium malate", gmo_id: "GMO_001527" },
  { name: "Calcium nitrate", gmo_id: "GMO_001193" },
  { name: "Calcium nitrate tetrahydrate", gmo_id: "GMO_001116" },
  { name: "Calcium pantothenate", gmo_id: "GMO_001028" },
  { name: "Calcium sulfate", gmo_id: "GMO_001882" },
  { name: "Calcium sulfate dihydrate", gmo_id: "GMO_001087" },
  { name: "Calcium sulfate heptahydrate", gmo_id: "GMO_001525" },
  { name: "Carboxymethyl cellulose; CMC, Carmellose", gmo_id: "GMO_001284" },
  { name: "Carrot", gmo_id: "GMO_001212" },
  { name: "Casamino acid", gmo_id: "GMO_001113" },
  { name: "Casamino acid solution", gmo_id: "GMO_001483" },
  { name: "Casein", gmo_id: "GMO_001531" },
  { name: "Casein (Sigma)", gmo_id: "GMO_001316" },
  { name: "Casein peptone", gmo_id: "GMO_001245" },
  { name: "Casein sodium; Casein sodium salt, Sodium caseinate", gmo_id: "GMO_001402" },
  { name: "Catalase", gmo_id: "GMO_001343" },
  { name: "Catalase from bovine liver C-10 (Sigma)", gmo_id: "GMO_001532" },
  { name: "Cellobiose", gmo_id: "GMO_001137" },
  { name: "Cellobiose solution", gmo_id: "GMO_001484" },
  { name: "Cellulose", gmo_id: "GMO_001180" },
  { name: "Cellulose (MN 300)", gmo_id: "GMO_001222" },
  { name: "Chalcopyrite", gmo_id: "GMO_001533" },
  { name: "Charcoal", gmo_id: "GMO_001896" },
  { name: "Cheese whey", gmo_id: "GMO_001259" },
  { name: "Chitosan", gmo_id: "GMO_001412" },
  { name: "Chloramphenicol", gmo_id: "GMO_001347" },
  { name: "Cholesterol; Cholesterin", gmo_id: "GMO_001821" },
  { name: "Choline chloride", gmo_id: "GMO_001099" },
  { name: "Chrysalis extract", gmo_id: "GMO_001282" },
  { name: "Citric acid", gmo_id: "GMO_001112" },
  { name: "Cobalamin; Vitamin B12", gmo_id: "GMO_001034" },
  { name: "Cobalamin solution; Vitamin B12 solution", gmo_id: "GMO_001106" },
  { name: "Cobalt dichloride; Cobalt(II) chloride", gmo_id: "GMO_001309" },
  { name: "Cobalt dichloride hexahydrate; Cobalt(II) chloride hexahydrate", gmo_id: "GMO_001021" },
  { name: "Cobalt dichloride hexahydrate solution ", gmo_id: "GMO_001922" },
  { name: "Cobalt dichloride monohydrate", gmo_id: "GMO_001745" },
  { name: "Cobalt dichloride solution; Cobalt(II) chloride solution", gmo_id: "GMO_001535" },
  { name: "Cobalt(II) nitrate", gmo_id: "GMO_001883" },
  { name: "Cobalt(II) nitrate hexahydrate; Cobalt nitrate hexahydrate", gmo_id: "GMO_001110" },
  { name: "Cobalt(II) sulfate heptahydrate", gmo_id: "GMO_001050" },
  { name: "Coenzyme A", gmo_id: "GMO_001536" },
  { name: "Coenzyme A sodium salt", gmo_id: "GMO_001822" },
  { name: "Coenzyme M; Mercaptoethanesulfonic acid", gmo_id: "GMO_001165" },
  { name: "Coenzyme M solution; Mercaptoethanesulfonic acid solution", gmo_id: "GMO_001481" },
  { name: "Congo red", gmo_id: "GMO_001537" },
  { name: "Copper(II) chloride; Cupric chloride", gmo_id: "GMO_001542" },
  { name: "Copper(II) chloride dihydrate; Cupric chloride dihydrate", gmo_id: "GMO_001024" },
  { name: "Copper(II) chloride hexahydrate", gmo_id: "GMO_001755" },
  { name: "Copper(II) chloride monohydrate", gmo_id: "GMO_001746" },
  { name: "Copper(II) sulfate; Copper sulfate, Cupric sulfate", gmo_id: "GMO_001103" },
  { name: "Copper(II) sulfate dihydrate; Cupric sulfate dihydrate", gmo_id: "GMO_001754" },
  { name: "Copper(II) sulfate heptahydrate; Boothite", gmo_id: "GMO_001761" },
  { name: "Copper(II) sulfate heptahydrate solution", gmo_id: "GMO_001366" },
  { name: "Copper(II) sulfate pentahydrate; Cupric sulfate pentahydrate", gmo_id: "GMO_001039" },
  { name: "Copper(II) sulfate pentahydrate solution", gmo_id: "GMO_001476" },
  { name: "Corn and fish meal mixture (feed for birds)", gmo_id: "GMO_001365" },
  { name: "Corn starch", gmo_id: "GMO_001929" },
  { name: "Corn steep liquor", gmo_id: "GMO_001540" },
  { name: "Cornmeal extract", gmo_id: "GMO_001157" },
  { name: "Cow manure", gmo_id: "GMO_001301" },
  { name: "Cow's milk (whole fat)", gmo_id: "GMO_001541" },
  { name: "Creatine", gmo_id: "GMO_001706" },
  { name: "Crotonic acid", gmo_id: "GMO_001294" },
  { name: "Crotonic acid solution", gmo_id: "GMO_001918" },
  { name: "Cycloheximide", gmo_id: "GMO_001275" },
  { name: "Cysteine", gmo_id: "GMO_001318" },
  { name: "Cysteine hydrochloride", gmo_id: "GMO_001032" },
  { name: "Cysteine hydrochloride solution", gmo_id: "GMO_001827" },
  { name: "Cysteine solution", gmo_id: "GMO_001485" },
  { name: "Cytidine", gmo_id: "GMO_001422" },
  { name: "D-Alanine", gmo_id: "GMO_001370" },
  { name: "D-Arginine", gmo_id: "GMO_001768" },
  { name: "D-Asparagine", gmo_id: "GMO_001871" },
  { name: "D-Aspartic acid", gmo_id: "GMO_001771" },
  { name: "D-Cystine", gmo_id: "GMO_001772" },
  { name: "D-Fructose", gmo_id: "GMO_001123" },
  { name: "D-Fructose solution", gmo_id: "GMO_001464" },
  { name: "D-Galactose", gmo_id: "GMO_001876" },
  { name: "D-Glucose; Dextrose, grape sugar", gmo_id: "GMO_001010" },
  {
    name: "D-Glucose (anhydrous); Dextrose (anhydrous), Glucose (anhydrous)",
    gmo_id: "GMO_001826",
  },
  { name: "D-Glucuronic acid sodium salt", gmo_id: "GMO_001865" },
  { name: "D-Glutamic acid", gmo_id: "GMO_001774" },
  { name: "D-Glutamine", gmo_id: "GMO_001777" },
  { name: "D-Histidine", gmo_id: "GMO_001873" },
  { name: "D-Isoleucine", gmo_id: "GMO_001784" },
  { name: "D-Leucine", gmo_id: "GMO_001786" },
  { name: "D-Lysine", gmo_id: "GMO_001789" },
  { name: "D-Methionine ", gmo_id: "GMO_001792" },
  { name: "D-Pantothenic Acid hemicalcium salt", gmo_id: "GMO_001816" },
  { name: "D-Phenylalanine ", gmo_id: "GMO_001795" },
  { name: "D-Proline", gmo_id: "GMO_001798" },
  { name: "D-Serine", gmo_id: "GMO_001801" },
  { name: "D-Threonine", gmo_id: "GMO_001804" },
  { name: "D-Tryptophan", gmo_id: "GMO_001806" },
  { name: "D-Tyrosine", gmo_id: "GMO_001809" },
  { name: "D-Valine", gmo_id: "GMO_001812" },
  { name: "DL-Methionine; LD-Methionine", gmo_id: "GMO_001327" },
  { name: "DL-Tryptophan; LD-Tryptophan", gmo_id: "GMO_001385" },
  { name: "DL-alpha-Methylbutyric acid", gmo_id: "GMO_001175" },
  { name: "Daigo's IMK medium (Nihon seiyaku)", gmo_id: "GMO_001243" },
  { name: "Decane", gmo_id: "GMO_001707" },
  { name: "Defibrinated horse blood", gmo_id: "GMO_001439" },
  {
    name: "Deionized water; DI water, DM water, De-ionized water, Demineralized water",
    gmo_id: "GMO_001695",
  },
  { name: "Demineralized Water", gmo_id: "GMO_001930" },
  { name: "Deoxyadenosine; 2'-Deoxyadenosine", gmo_id: "GMO_001823" },
  { name: "Deoxycytidine hydrochloride; 2′-Deoxycytidine hydrochloride", gmo_id: "GMO_001825" },
  { name: "Deoxyguanosine; 2'-Deoxyguanosine", gmo_id: "GMO_001824" },
  { name: "Dextrin", gmo_id: "GMO_001268" },
  { name: "Diammonium hydrogen citrate", gmo_id: "GMO_001084" },
  { name: "Dichloran", gmo_id: "GMO_001414" },
  { name: "Difco Agar, noble", gmo_id: "GMO_001510" },
  { name: "Difco Casamino acids, vitamin assay", gmo_id: "GMO_001169" },
  { name: "Difco ISP medium 1; Tryptone-Yeast Extract Broth", gmo_id: "GMO_001291" },
  { name: "Difco LB agar, Lennox", gmo_id: "GMO_001895" },
  { name: "Difco LB broth, Lennox", gmo_id: "GMO_001435" },
  { name: "Difco Lactobacilli MRS broth", gmo_id: "GMO_001572" },
  { name: "Difco Legionella agar base", gmo_id: "GMO_001848" },
  { name: "Difco Legionella agar enrichment", gmo_id: "GMO_001574" },
  { name: "Difco Marine agar 2216", gmo_id: "GMO_001295" },
  { name: "Difco Marine broth 2216", gmo_id: "GMO_001095" },
  { name: "Difco Nutrient Agar", gmo_id: "GMO_001302" },
  { name: "Difco Nutrient broth", gmo_id: "GMO_001344" },
  { name: "Difco PPLO Broth; Difco PPLO Broth (w/o CV)", gmo_id: "GMO_001183" },
  { name: "Difco YM broth", gmo_id: "GMO_001682" },
  { name: "Difco Yeast carbon base", gmo_id: "GMO_001392" },
  { name: "Difco heart infusion agar", gmo_id: "GMO_001364" },
  { name: "Difco m TGE broth; membrane Tryptone Glucose Extract Broth", gmo_id: "GMO_001517" },
  { name: "Difco tryptic soy agar", gmo_id: "GMO_001229" },
  { name: "Digested serum", gmo_id: "GMO_001850" },
  { name: "Dimethyl sulfoxide", gmo_id: "GMO_001544" },
  { name: "Disodio persulfide nonahydrate", gmo_id: "GMO_001601" },
  { name: "Disodium EDTA", gmo_id: "GMO_001058" },
  { name: "Disodium EDTA dihydrate", gmo_id: "GMO_001148" },
  { name: "Disodium fumarate", gmo_id: "GMO_001298" },
  { name: "Disodium fumarate solution", gmo_id: "GMO_001729" },
  { name: "Disodium phosphate", gmo_id: "GMO_001069" },
  { name: "Disodium phosphate dihydrate", gmo_id: "GMO_001155" },
  { name: "Disodium phosphate dodecahydrate", gmo_id: "GMO_001115" },
  {
    name: "Disodium phosphate heptahydrate; Disodium hydrogen phosphate heptahydrate",
    gmo_id: "GMO_001189",
  },
  { name: "Disodium phosphate hexahydrate", gmo_id: "GMO_001599" },
  { name: "Disodium phosphate solution", gmo_id: "GMO_001505" },
  { name: "Disodium phosphate-Monosodium phosphate buffer", gmo_id: "GMO_001600" },
  { name: "Disodium selenate", gmo_id: "GMO_001111" },
  { name: "Disodium succinate", gmo_id: "GMO_001177" },
  {
    name: "Disodium sulfide-Cysteine solution; Sodium sulfide-Cysteine solution",
    gmo_id: "GMO_001373",
  },
  { name: "Disodium tetraborate", gmo_id: "GMO_001187" },
  { name: "Distilled water", gmo_id: "GMO_001001" },
  { name: "Dithionite", gmo_id: "GMO_001261" },
  { name: "Dithionite solution", gmo_id: "GMO_001279" },
  { name: "Dithiothreitol; DTT", gmo_id: "GMO_001545" },
  { name: "Dithiothreitol solution", gmo_id: "GMO_001502" },
  { name: "Dried shrimp", gmo_id: "GMO_001310" },
  { name: "Dried yeast extract D-3", gmo_id: "GMO_001409" },
  { name: "Dried yeast extract S (Wako)", gmo_id: "GMO_001546" },
  { name: "Dry yeast", gmo_id: "GMO_001260" },
  { name: "EDTA; Ethylenediaminetetraacetic acid", gmo_id: "GMO_001237" },
  {
    name: "EDTA monosodium Iron(III) salt ; EDTA-Na-Fe(III), Ethylenediaminetetraacetic acid monosodium iron(III) salt",
    gmo_id: "GMO_001759",
  },
  { name: "EDTA monosodium iron(III) solution", gmo_id: "GMO_001921" },
  { name: "EDTA solution ", gmo_id: "GMO_001920" },
  { name: "Ebios (tablets)", gmo_id: "GMO_001226" },
  { name: "Environmental water", gmo_id: "GMO_001407" },
  { name: "Estradiol", gmo_id: "GMO_001264" },
  { name: "Ethanol; Ethyl alcohol, エチルアルコール", gmo_id: "GMO_001114" },
  { name: "Extract", gmo_id: "GMO_000011" },
  { name: "FAD; Flavin adenine dinucleotide", gmo_id: "GMO_001547" },
  {
    name: "FAD disodium salt; Flavin Adenine Dinucleotide•2Na, Flavin adenine dinucleotide disodium salt",
    gmo_id: "GMO_001862",
  },
  { name: "Fe(III)-EDTA", gmo_id: "GMO_001139" },
  { name: "Fetal bovine serum", gmo_id: "GMO_001552" },
  { name: "Fetal bovine serum (heat-inactivated)", gmo_id: "GMO_001397" },
  { name: "Fish meat extract", gmo_id: "GMO_001554" },
  { name: "Fluka Fish peptone", gmo_id: "GMO_001919" },
  { name: "Folic acid; Folate, Vitamin B9, Vitamin M", gmo_id: "GMO_001033" },
  { name: "Fresh baker's yeast extract solution", gmo_id: "GMO_001429" },
  { name: "GAM agar (Nissui)", gmo_id: "GMO_001556" },
  { name: "GAM agar, modified (Nissui)", gmo_id: "GMO_001557" },
  { name: "GAM broth (Nissui)", gmo_id: "GMO_001285" },
  { name: "GAM broth, modified (Nissui)", gmo_id: "GMO_001858" },
  { name: "Galactose", gmo_id: "GMO_001206" },
  { name: "Gelatin", gmo_id: "GMO_001395" },
  { name: "Gellan gum", gmo_id: "GMO_001250" },
  { name: "Gentisic acid", gmo_id: "GMO_001437" },
  { name: "Glacial acetic acid", gmo_id: "GMO_001558" },
  { name: "Glucose", gmo_id: "GMO_001815" },
  { name: "Glucose solution", gmo_id: "GMO_001465" },
  { name: "Glutamate", gmo_id: "GMO_001324" },
  { name: "Glutamic acid", gmo_id: "GMO_001773" },
  { name: "Glutamine", gmo_id: "GMO_001775" },
  { name: "Glutathione", gmo_id: "GMO_001328" },
  { name: "Glycerol; Glycerin", gmo_id: "GMO_001083" },
  { name: "Glycerol 3-phosphate", gmo_id: "GMO_001138" },
  { name: "Glycerol monostearate", gmo_id: "GMO_001273" },
  { name: "Glycerol solution", gmo_id: "GMO_001466" },
  { name: "Glycine", gmo_id: "GMO_001559" },
  { name: "Glycine-Sodium hydroxide buffer", gmo_id: "GMO_001461" },
  { name: "Glycylglycine", gmo_id: "GMO_001430" },
  { name: "Ground Sesami powder", gmo_id: "GMO_001358" },
  { name: "Ground beef (fat free)", gmo_id: "GMO_001388" },
  { name: "Guaiacol", gmo_id: "GMO_001426" },
  { name: "HEPES; 4-(2-hydroxyethyl)-1-piperazineethanesulfonic acid", gmo_id: "GMO_001142" },
  { name: "HEPES (Sigma)", gmo_id: "GMO_001749" },
  { name: "HEPES (free acid)", gmo_id: "GMO_001750" },
  {
    name: "HEPES buffer; 4-(2-hydroxyethyl)-1-piperazineethanesulfonic acid",
    gmo_id: "GMO_001738",
  },
  { name: "Hemin; Hematin", gmo_id: "GMO_001312" },
  { name: "Hemin chloride", gmo_id: "GMO_001561" },
  { name: "Hemin from bovine solution; Bovine hemin chloride solution", gmo_id: "GMO_001519" },
  { name: "Hemin solution", gmo_id: "GMO_001449" },
  {
    name: "Hexaammonium heptamolybdate tetrahydrate; AC1LACDZ, Ammonium heptamolybdate tetrahydrate, Ammonium molybdate tetrahydrate",
    gmo_id: "GMO_001221",
  },
  { name: "Hexanoic acid; Caproic acid", gmo_id: "GMO_001528" },
  { name: "Hipolypepton (Nihon seiyaku); Polypepton", gmo_id: "GMO_001322" },
  { name: "Histidine", gmo_id: "GMO_001170" },
  {
    name: "Homo-PIPES; HomoPIPES, Homopiperazine-1,4-bis(2-ethanesulfonic acid), Hexahydro-1H-1,4-diazepine-1,4-bis(2-ethanesulfonic acid)",
    gmo_id: "GMO_001924",
  },
  { name: "Horse blood", gmo_id: "GMO_001562" },
  { name: "Horse serum", gmo_id: "GMO_001127" },
  { name: "Humic acid", gmo_id: "GMO_001433" },
  { name: "Hunter's basal salts", gmo_id: "GMO_001202" },
  { name: "Hy-case amino (Sigma)", gmo_id: "GMO_001563" },
  { name: "Hydrochloric acid", gmo_id: "GMO_001048" },
  { name: "Hydrochloric acid solution", gmo_id: "GMO_001499" },
  { name: "Hydroxyproline", gmo_id: "GMO_001779" },
  {
    name: "Indigo carmine; 5,5'-indigodisulfonic acid sodium salt, indigotine",
    gmo_id: "GMO_001564",
  },
  { name: "Infusion from Beef heart; Beef heart, infusion from", gmo_id: "GMO_001831" },
  { name: "Infusion from Liver; Liver, infusion from", gmo_id: "GMO_001145" },
  { name: "Infusion from calf brain; Calf brain, infusion from", gmo_id: "GMO_001832" },
  { name: "Infusion from heart muscle; Heart muscle, infusion from", gmo_id: "GMO_001834" },
  { name: "Inositol", gmo_id: "GMO_001101" },
  { name: "Iron", gmo_id: "GMO_001565" },
  { name: "Iron granule", gmo_id: "GMO_001410" },
  { name: "Iron stock solution", gmo_id: "GMO_001912" },
  { name: "Iron(II) chloride; Ferrous chloride", gmo_id: "GMO_001270" },
  { name: "Iron(II) chloride hexahydrate; Iron dichloride hexahydrate", gmo_id: "GMO_001549" },
  {
    name: "Iron(II) chloride hexahydrate solution; Iron dichloride hexahydrate solution",
    gmo_id: "GMO_001490",
  },
  { name: "Iron(II) chloride solution", gmo_id: "GMO_001488" },
  { name: "Iron(II) chloride tetrahydrate; Iron dichloride tetrahydrate", gmo_id: "GMO_001548" },
  { name: "Iron(II) citrate; Ferrous citrate", gmo_id: "GMO_001716" },
  { name: "Iron(II) sulfate; Ferrous sulfate", gmo_id: "GMO_001337" },
  { name: "Iron(II) sulfate heptahydrate; Ferrous sulfate heptahydrate", gmo_id: "GMO_001016" },
  {
    name: "Iron(II) sulfate heptahydrate solution; Ferrous sulfate heptahydrate solution",
    gmo_id: "GMO_001353",
  },
  { name: "Iron(II) sulfate hexahydrate; Ferrous sulfate hexahydrate", gmo_id: "GMO_001550" },
  {
    name: "Iron(II) sulfate hexahydrate solution; Ferrous sulfate hexahydrate solution",
    gmo_id: "GMO_001456",
  },
  { name: "Iron(II) sulfate monohydrate; Ferrous sulfate monohydrate", gmo_id: "GMO_001551" },
  {
    name: "Iron(II) sulfate pentahydrate solution; Ferrous sulfate pentahydrate solution",
    gmo_id: "GMO_001700",
  },
  { name: "Iron(II) sulfate solution; Ferrous sulfate solution", gmo_id: "GMO_001393" },
  { name: "Iron(III) chloride; Ferric chloride", gmo_id: "GMO_001122" },
  { name: "Iron(III) chloride hexahydrate", gmo_id: "GMO_001047" },
  { name: "Iron(III) chloride monohydrate", gmo_id: "GMO_001747" },
  { name: "Iron(III) chloride solution", gmo_id: "GMO_001715" },
  { name: "Iron(III) chloride tetrahydrate", gmo_id: "GMO_001293" },
  { name: "Iron(III) citrate; Ferric citrate", gmo_id: "GMO_001118" },
  { name: "Iron(III) citrate solution", gmo_id: "GMO_001079" },
  { name: "Iron(III) oxide, poorly crystalline, solution", gmo_id: "GMO_001907" },
  { name: "Iron(III) pyrophosphate; Ferric pyrophosphate", gmo_id: "GMO_001846" },
  { name: "Iron(III) sulfate; Ferric sulfate", gmo_id: "GMO_001211" },
  { name: "Iron(III) sulfate n-hydrate", gmo_id: "GMO_001304" },
  { name: "Isobutyric acid; 2-methylpropanoic acid", gmo_id: "GMO_001184" },
  { name: "Isoleucine", gmo_id: "GMO_001782" },
  { name: "Isovaleric acid; 3-Methylbutanoic acid", gmo_id: "GMO_001182" },
  { name: "Kanamycin solution", gmo_id: "GMO_001384" },
  { name: "Kanamycin sulfate solution", gmo_id: "GMO_001371" },
  { name: "Keratin", gmo_id: "GMO_001389" },
  { name: "L-Alanine", gmo_id: "GMO_001766" },
  { name: "L-Arginine", gmo_id: "GMO_001767" },
  { name: "L-Arginine monohydrochloride", gmo_id: "GMO_001887" },
  { name: "L-Ascorbic acid; Vitamin C", gmo_id: "GMO_001813" },
  { name: "L-Asparagine", gmo_id: "GMO_001870" },
  { name: "L-Asparagine monohydrate", gmo_id: "GMO_001888" },
  { name: "L-Aspartic acid", gmo_id: "GMO_001770" },
  { name: "L-Cysteine hydrochloride", gmo_id: "GMO_001828" },
  { name: "L-Cysteine hydrochloride monohydrate", gmo_id: "GMO_001205" },
  { name: "L-Cysteine hydrochloride monohydrate solution", gmo_id: "GMO_001496" },
  { name: "L-Cystine", gmo_id: "GMO_001331" },
  { name: "L-Cystine dihydrochloride", gmo_id: "GMO_001886" },
  { name: "L-Cystine hydrochloride monohydrate", gmo_id: "GMO_001569" },
  { name: "L-Glutamic acid", gmo_id: "GMO_001570" },
  { name: "L-Glutamic acid sodium salt", gmo_id: "GMO_001889" },
  { name: "L-Glutamine", gmo_id: "GMO_001776" },
  { name: "L-Histidine", gmo_id: "GMO_001872" },
  { name: "L-Histidine monohydrochloride", gmo_id: "GMO_001762" },
  { name: "L-Histidine monohydrochloride monohydrate", gmo_id: "GMO_001778" },
  { name: "L-Isoleucine", gmo_id: "GMO_001783" },
  { name: "L-Leucine", gmo_id: "GMO_001785" },
  { name: "L-Lysine", gmo_id: "GMO_001788" },
  { name: "L-Lysine monohydrochloride; L-Lysine HCl", gmo_id: "GMO_001790" },
  { name: "L-Methionine ", gmo_id: "GMO_001791" },
  { name: "L-Phenylalanine ", gmo_id: "GMO_001794" },
  { name: "L-Proline", gmo_id: "GMO_001797" },
  { name: "L-Serine", gmo_id: "GMO_001800" },
  { name: "L-Serine solution", gmo_id: "GMO_001899" },
  { name: "L-Threonine", gmo_id: "GMO_001803" },
  { name: "L-Tryptophan", gmo_id: "GMO_001805" },
  { name: "L-Tyrosine", gmo_id: "GMO_001808" },
  { name: "L-Tyrosine disodium salt dihydrate", gmo_id: "GMO_001874" },
  { name: "L-Valine", gmo_id: "GMO_001811" },
  { name: "LB medium; Lysogeny broth", gmo_id: "GMO_001842" },
  { name: "LB medium, Lennox", gmo_id: "GMO_001845" },
  { name: "LB medium, Luria", gmo_id: "GMO_001844" },
  { name: "LB medium, Miller", gmo_id: "GMO_001843" },
  { name: "Lab Lemco", gmo_id: "GMO_001217" },
  { name: "Lactose", gmo_id: "GMO_001445" },
  { name: "Larchwood xylan (Sigma); Larch wood xylan (Sigma)", gmo_id: "GMO_001573" },
  { name: "Leibovitz's L-15 medium", gmo_id: "GMO_001741" },
  { name: "Leucine", gmo_id: "GMO_001411" },
  { name: "Lipoic acid; Thioctic acid, alpha Lipoic acid", gmo_id: "GMO_001699" },
  { name: "Lithium chloride", gmo_id: "GMO_001431" },
  { name: "Liver extract", gmo_id: "GMO_001830" },
  { name: "Liver extract concentrate (NBCo)", gmo_id: "GMO_001742" },
  { name: "Lysine", gmo_id: "GMO_001787" },
  { name: "M17 broth (Oxoid)", gmo_id: "GMO_001376" },
  { name: "MES; 2-(N-morpholino)ethanesulfonic acid", gmo_id: "GMO_001191" },
  { name: "MES solution", gmo_id: "GMO_001733" },
  { name: "MJ(-N) synthetic seawater", gmo_id: "GMO_001900" },
  { name: "MOPS; 3-(N-morpholino)propanesulfonic acid", gmo_id: "GMO_001152" },
  { name: "MOPS solution", gmo_id: "GMO_001480" },
  { name: "Magnesium acetate", gmo_id: "GMO_001188" },
  { name: "Magnesium chloride", gmo_id: "GMO_001154" },
  { name: "Magnesium chloride dihydrate", gmo_id: "GMO_001266" },
  { name: "Magnesium chloride heptahydrate", gmo_id: "GMO_001586" },
  { name: "Magnesium chloride hexahydrate", gmo_id: "GMO_001013" },
  { name: "Magnesium chloride hexahydrate solution", gmo_id: "GMO_001286" },
  { name: "Magnesium chloride monohydrate", gmo_id: "GMO_001171" },
  { name: "Magnesium chloride monohydrate solution", gmo_id: "GMO_001697" },
  { name: "Magnesium chloride pentahydrate", gmo_id: "GMO_001585" },
  {
    name: "Magnesium glycerophosphate; DL-alpha-Glycerol phosphate magnesium salt hydrate",
    gmo_id: "GMO_001841",
  },
  { name: "Magnesium nitrate", gmo_id: "GMO_001884" },
  { name: "Magnesium nitrate hexahydrate", gmo_id: "GMO_001584" },
  { name: "Magnesium oxide", gmo_id: "GMO_001199" },
  { name: "Magnesium sulfate; Magnesium sulphate", gmo_id: "GMO_001096" },
  { name: "Magnesium sulfate anhydrate", gmo_id: "GMO_001818" },
  { name: "Magnesium sulfate heptahydrate", gmo_id: "GMO_001002" },
  { name: "Magnesium sulfate heptahydrate solution", gmo_id: "GMO_001463" },
  { name: "Magnesium sulfate hexahydrate", gmo_id: "GMO_001446" },
  { name: "Magnesium sulfate monohydrate", gmo_id: "GMO_001587" },
  { name: "Magnesium sulfate solution", gmo_id: "GMO_001451" },
  { name: "Malachite green", gmo_id: "GMO_001885" },
  { name: "Malachite green solution", gmo_id: "GMO_001493" },
  { name: "Malonic acid; Propanedioic acid", gmo_id: "GMO_001428" },
  { name: "Malt extract", gmo_id: "GMO_001059" },
  { name: "Malt extract agar (Nissui)", gmo_id: "GMO_001306" },
  { name: "Malted wheat meal", gmo_id: "GMO_001578" },
  { name: "Maltose; Malt sugar, Maltobiose", gmo_id: "GMO_001195" },
  { name: "Maltose monohydrate", gmo_id: "GMO_001579" },
  { name: "Maltose, technical (Difco)", gmo_id: "GMO_001580" },
  { name: "Manganese EDTA; Mn-EDTA", gmo_id: "GMO_001839" },
  { name: "Manganese chloride", gmo_id: "GMO_001589" },
  { name: "Manganese chloride dihydrate; Manganous chloride dihydrate", gmo_id: "GMO_001129" },
  { name: "Manganese chloride hexahydrate", gmo_id: "GMO_001591" },
  { name: "Manganese chloride monohydrate", gmo_id: "GMO_001592" },
  { name: "Manganese chloride tetrahydrate", gmo_id: "GMO_001020" },
  { name: "Manganese sulfate", gmo_id: "GMO_001763" },
  { name: "Manganese sulfate dihydrate", gmo_id: "GMO_001068" },
  { name: "Manganese sulfate heptahydrate; Manganous sulfate heptahydrate", gmo_id: "GMO_001381" },
  { name: "Manganese sulfate monohydrate", gmo_id: "GMO_001081" },
  { name: "Manganese sulfate n-hydrate; Manganese sulfate x-hydrate", gmo_id: "GMO_001065" },
  { name: "Manganese sulfate pentahydrate", gmo_id: "GMO_001150" },
  { name: "Manganese sulfate solution", gmo_id: "GMO_001342" },
  { name: "Manganese sulfate tetrahydrate", gmo_id: "GMO_001064" },
  { name: "Mannitol", gmo_id: "GMO_001135" },
  { name: "MeM alpha modification (BioWest)", gmo_id: "GMO_001581" },
  { name: "Meat extract", gmo_id: "GMO_001074" },
  { name: "Meat peptone", gmo_id: "GMO_001868" },
  { name: "Melibiose", gmo_id: "GMO_001582" },
  { name: "Menadione; Vitamin K3", gmo_id: "GMO_001908" },
  { name: "Menadione solution", gmo_id: "GMO_001909" },
  { name: 'Metals "44"', gmo_id: "GMO_001856" },
  { name: "Methanol; Methyl alcohol, Methyl alcohol", gmo_id: "GMO_001082" },
  { name: "Methanol solution", gmo_id: "GMO_001508" },
  { name: "Methionine", gmo_id: "GMO_001378" },
  { name: "Methylamine", gmo_id: "GMO_001583" },
  { name: "Methylamine hydrochloride", gmo_id: "GMO_001303" },
  { name: "Mevalonic acid", gmo_id: "GMO_001368" },
  { name: "Middlebrook 7H10 agar (Difco)", gmo_id: "GMO_001588" },
  { name: "Milli-Q water; MilliQ water", gmo_id: "GMO_001743" },
  { name: "Molybdenum trioxide", gmo_id: "GMO_001252" },
  {
    name: "Monopotassium phosphite; Monobasic potassium phosphate, Potassium dihydrogen phosphate, Potassium;dihydrogen phosphite",
    gmo_id: "GMO_001714",
  },
  { name: "Monosodium EDTA", gmo_id: "GMO_001161" },
  { name: "Mueller hinton II agar (BBL)", gmo_id: "GMO_001595" },
  { name: "Murashige & Skoog's plant salt mixture", gmo_id: "GMO_001311" },
  { name: "N-Z-Amine A (Sheffield)", gmo_id: "GMO_001140" },
  { name: "N-Z-Case (Wako)", gmo_id: "GMO_001597" },
  { name: "N-acetylglucosamine; GlcNAc, N-acetyl-D-glucosamine", gmo_id: "GMO_001404" },
  { name: "N-acetylglucosamine (Sigma); GlcNAc, N-acetyl-D-glucosamine", gmo_id: "GMO_001708" },
  { name: "Naphthalene", gmo_id: "GMO_001307" },
  { name: "Neutral red", gmo_id: "GMO_001897" },
  { name: "Neutralized sulfide solution", gmo_id: "GMO_001105" },
  { name: "Nickel ammonium sulfate", gmo_id: "GMO_001280" },
  {
    name: "Nickel ammonium sulfate hexahydrate; Diammonium nickel disulfate hexahydrate",
    gmo_id: "GMO_001102",
  },
  { name: "Nickel chloride", gmo_id: "GMO_001611" },
  { name: "Nickel chloride hexahydrate", gmo_id: "GMO_001022" },
  { name: "Nickel chloride hexahydrate solution", gmo_id: "GMO_001923" },
  { name: "Nickel chloride hydrate", gmo_id: "GMO_001612" },
  { name: "Nickel chloride pentahydrate", gmo_id: "GMO_001760" },
  { name: "Nickel(II) sulfate heptahydrate", gmo_id: "GMO_001613" },
  { name: "Nickel(II) sulfate hexahydrate", gmo_id: "GMO_001136" },
  { name: "Nicotinamide; Niacinamide, Nicotinic acid amide", gmo_id: "GMO_001162" },
  { name: "Nicotinic acid; Niacin, Vitamin B3", gmo_id: "GMO_001038" },
  { name: "Nitrilotriacetic acid; NTA", gmo_id: "GMO_001053" },
  { name: "Nitrilotriacetic acid disodium salt solution", gmo_id: "GMO_001758" },
  { name: "Nitrilotriacetic acid trisodium salt", gmo_id: "GMO_001756" },
  { name: "Nitrilotriacetic acid trisodium salt monohydrate", gmo_id: "GMO_001752" },
  { name: "Oatmeal", gmo_id: "GMO_001134" },
  { name: "Olive oil", gmo_id: "GMO_001218" },
  { name: "Ox bile desiccated", gmo_id: "GMO_001421" },
  { name: "Oxgall (Difco)", gmo_id: "GMO_001614" },
  { name: "Oxioid Cooked meat medium", gmo_id: "GMO_001538" },
  { name: "Oxoid Czapek-dox liquid medium, modified", gmo_id: "GMO_001377" },
  { name: "Oxoid Lab-lemco beef extract powder", gmo_id: "GMO_001690" },
  { name: "Oxoid Lab-lemco broth", gmo_id: "GMO_001420" },
  { name: "Oxoid Malt extract agar", gmo_id: "GMO_001577" },
  { name: "Oxoid Mycological peptone", gmo_id: "GMO_001851" },
  { name: "Oxoid Nutrient broth", gmo_id: "GMO_001176" },
  { name: "Oxoid Peptonized milk", gmo_id: "GMO_001313" },
  { name: "Oxoid Tryptone soya broth", gmo_id: "GMO_001672" },
  { name: "PIPES; Piperazine-N,N′-bis(2-ethanesulfonic acid)", gmo_id: "GMO_001223" },
  { name: "PIPES (Sigma)", gmo_id: "GMO_001723" },
  { name: "PIPES solution", gmo_id: "GMO_001448" },
  { name: "Pancreatic digest of casein", gmo_id: "GMO_001615" },
  { name: "Pantothenic acid; Pantothenate, Vitamin B5", gmo_id: "GMO_001616" },
  { name: "Papaic digest of soybean", gmo_id: "GMO_001835" },
  { name: "Pectin", gmo_id: "GMO_001617" },
  { name: "Penicillin", gmo_id: "GMO_001618" },
  { name: "Peptic digest of animal tissue", gmo_id: "GMO_001619" },
  { name: "Peptic peptone (USB)", gmo_id: "GMO_001413" },
  { name: "Peptone", gmo_id: "GMO_000012" },
  { name: "Peptone (Oxoid)", gmo_id: "GMO_001620" },
  { name: "Peptone solution", gmo_id: "GMO_001734" },
  { name: "Phenanthrene", gmo_id: "GMO_001334" },
  { name: "Phenol red; Phenolsulfonphthalein", gmo_id: "GMO_001156" },
  { name: "Phenol red sodium salt; Sodium phenol red", gmo_id: "GMO_001864" },
  { name: "Phenol red solution; Phenolsulfonphthalein solution", gmo_id: "GMO_001460" },
  { name: "Phenol solution", gmo_id: "GMO_001728" },
  { name: "Phenylalanine", gmo_id: "GMO_001793" },
  { name: "Phosphate buffer", gmo_id: "GMO_001916" },
  { name: "Phosphate buffer (pH 7.2)", gmo_id: "GMO_001915" },
  { name: "Phthalic acid", gmo_id: "GMO_001444" },
  { name: "Plant extract", gmo_id: "GMO_001859" },
  { name: "Polyethylene glycol", gmo_id: "GMO_001425" },
  { name: "Polypeptone", gmo_id: "GMO_001080" },
  { name: "Polysorbate 20; Tween 20", gmo_id: "GMO_001675" },
  { name: "Polysorbate 60; Tween 60", gmo_id: "GMO_001386" },
  { name: "Polysorbate 80; Tween 80", gmo_id: "GMO_001060" },
  { name: "Potassium acetate", gmo_id: "GMO_001724" },
  { name: "Potassium bicarbonate", gmo_id: "GMO_001317" },
  { name: "Potassium bromide", gmo_id: "GMO_001108" },
  { name: "Potassium chloride", gmo_id: "GMO_001017" },
  { name: "Potassium hydroxide", gmo_id: "GMO_001902" },
  { name: "Potassium hydroxide solution", gmo_id: "GMO_001903" },
  { name: "Potassium iodide", gmo_id: "GMO_001091" },
  { name: "Potassium nitrate", gmo_id: "GMO_001056" },
  { name: "Potassium nitrate solution", gmo_id: "GMO_001469" },
  { name: "Potassium phosphate buffer", gmo_id: "GMO_001308" },
  {
    name: "Potassium phosphate dibasic; Dipotassium hydrogen phosphate, Dipotassium phosphate",
    gmo_id: "GMO_001009",
  },
  { name: "Potassium phosphate dibasic solution", gmo_id: "GMO_001467" },
  {
    name: "Potassium phosphate dibasic trihydrate; Dipotassium phosphate trihydrate",
    gmo_id: "GMO_001125",
  },
  { name: "Potassium phosphate monobasic; Monopotassium phosphate", gmo_id: "GMO_001006" },
  {
    name: "Potassium phosphate monobasic dihydrate; Monopotassium phosphate dihydrate",
    gmo_id: "GMO_001568",
  },
  { name: "Potassium phosphate monobasic solution", gmo_id: "GMO_001468" },
  { name: "Potassium sulfate", gmo_id: "GMO_001173" },
  { name: "Potassium sulfate heptahydrate", gmo_id: "GMO_001567" },
  { name: "Potassium tetrathionate", gmo_id: "GMO_001566" },
  { name: "Potassium tetrathionate solution", gmo_id: "GMO_001450" },
  { name: "Potassium thiocyanate", gmo_id: "GMO_001241" },
  { name: "Potassium thiocyanate solution", gmo_id: "GMO_001492" },
  { name: "Potato", gmo_id: "GMO_001092" },
  { name: "Potato dextrose agar (Nissui)", gmo_id: "GMO_001374" },
  { name: "Prepared culture medium", gmo_id: "GMO_000019" },
  { name: "Press yeast", gmo_id: "GMO_001174" },
  { name: "Probumin universal grade (Merck Millipore)", gmo_id: "GMO_001625" },
  { name: "Proline", gmo_id: "GMO_001796" },
  { name: "Propionic acid; Propionic acid", gmo_id: "GMO_001192" },
  { name: "Proteose peptone", gmo_id: "GMO_001185" },
  { name: "Pullulan", gmo_id: "GMO_001725" },
  { name: "Purified agar", gmo_id: "GMO_001423" },
  { name: "Purified water", gmo_id: "GMO_001890" },
  { name: "Putrescine", gmo_id: "GMO_001628" },
  { name: "Pyridoxal hydrochloride", gmo_id: "GMO_001167" },
  { name: "Pyridoxal phosphate; PLP", gmo_id: "GMO_001629" },
  { name: "Pyridoxamine; Vitamin B6", gmo_id: "GMO_001751" },
  { name: "Pyridoxamine dihydrochloride", gmo_id: "GMO_001630" },
  { name: "Pyridoxamine hydrochloride", gmo_id: "GMO_001631" },
  { name: "Pyridoxine; Vitamin B6", gmo_id: "GMO_001632" },
  { name: "Pyridoxine dihydrochloride", gmo_id: "GMO_001253" },
  { name: "Pyridoxine hydrochloride", gmo_id: "GMO_001029" },
  { name: "Pyruvate solution", gmo_id: "GMO_001263" },
  { name: "Quinic acid", gmo_id: "GMO_001248" },
  { name: "Quinic acid solution", gmo_id: "GMO_001740" },
  { name: "R2A agar (Difco)", gmo_id: "GMO_001633" },
  { name: "R2A broth DAIGO (Nihon seiyaku)", gmo_id: "GMO_001213" },
  { name: "Rabbit blood", gmo_id: "GMO_001634" },
  { name: "Rabbit serum", gmo_id: "GMO_001635" },
  { name: "Raffinose", gmo_id: "GMO_001210" },
  { name: "Reinforced clostridial agar (Sigma)", gmo_id: "GMO_001636" },
  { name: "Reinforced clostridial medium (Difco)", gmo_id: "GMO_001637" },
  { name: "Reinforced clostridial medium (Oxoid)", gmo_id: "GMO_001242" },
  { name: "Resazurin; 7-Hydroxy-3H-phenoxazin-3-one 10-oxide", gmo_id: "GMO_001012" },
  { name: "Resazurin solution", gmo_id: "GMO_001403" },
  { name: "Rhamnose", gmo_id: "GMO_001272" },
  { name: "Riboflavin; Vitamin B2", gmo_id: "GMO_001037" },
  { name: "Riboflavin 5'-monophosphate sodium salt dihydrate", gmo_id: "GMO_001875" },
  { name: "Ribose", gmo_id: "GMO_001638" },
  { name: "Rifampicin solution", gmo_id: "GMO_001164" },
  { name: "Rumen fluid", gmo_id: "GMO_001727" },
  { name: "Rumen fluid (clarified)", gmo_id: "GMO_001534" },
  { name: "Rye-bran", gmo_id: "GMO_001639" },
  { name: "Rye-bran extract", gmo_id: "GMO_001640" },
  { name: "SOB medium; Super Optimal Broth", gmo_id: "GMO_001966" },
  { name: "Sake", gmo_id: "GMO_001641" },
  { name: "Se-W solution", gmo_id: "GMO_001857" },
  { name: "Se/W solution", gmo_id: "GMO_001121" },
  { name: "Sea salts (SIGMA)", gmo_id: "GMO_001231" },
  { name: "Sea water filtered", gmo_id: "GMO_001447" },
  { name: "Seawater", gmo_id: "GMO_001066" },
  { name: "Selenium salt", gmo_id: "GMO_001642" },
  { name: "Selenous acid; Selenious acid", gmo_id: "GMO_001717" },
  { name: "Serine", gmo_id: "GMO_001799" },
  { name: "Serum-derived component", gmo_id: "GMO_001879" },
  { name: "Sheep blood, defibrinated", gmo_id: "GMO_001506" },
  { name: "Silicone based defoamers", gmo_id: "GMO_001840" },
  { name: "Skim milk", gmo_id: "GMO_001172" },
  { name: "Skim milk (Difco)", gmo_id: "GMO_001643" },
  { name: "Sludge fluid", gmo_id: "GMO_001296" },
  { name: "Sodium DL-lactate", gmo_id: "GMO_001644" },
  { name: "Sodium DL-malate", gmo_id: "GMO_001645" },
  { name: "Sodium L-lactate", gmo_id: "GMO_001362" },
  { name: "Sodium L-malate", gmo_id: "GMO_001646" },
  { name: "Sodium acetate; NaOAc, Sodium ethanoate", gmo_id: "GMO_001031" },
  { name: "Sodium acetate solution", gmo_id: "GMO_001415" },
  { name: "Sodium acetate trihydrate", gmo_id: "GMO_001396" },
  { name: "Sodium alginate", gmo_id: "GMO_001443" },
  { name: "Sodium ampicillin solution", gmo_id: "GMO_001436" },
  { name: "Sodium ascorbate", gmo_id: "GMO_001225" },
  { name: "Sodium ascorbate solution", gmo_id: "GMO_001478" },
  { name: "Sodium aspartate", gmo_id: "GMO_001330" },
  { name: "Sodium benzoate", gmo_id: "GMO_001336" },
  { name: "Sodium benzoate solution", gmo_id: "GMO_001509" },
  { name: "Sodium bicarbonate; Sodium hydrogen carbonate", gmo_id: "GMO_001019" },
  { name: "Sodium bicarbonate (Sigma)", gmo_id: "GMO_001607" },
  { name: "Sodium bicarbonate solution", gmo_id: "GMO_001119" },
  { name: "Sodium bisulfite", gmo_id: "GMO_001608" },
  { name: "Sodium bromide", gmo_id: "GMO_001073" },
  { name: "Sodium butyrate", gmo_id: "GMO_001648" },
  { name: "Sodium butyrate solution", gmo_id: "GMO_001473" },
  { name: "Sodium carbonate", gmo_id: "GMO_001045" },
  { name: "Sodium carbonate solution", gmo_id: "GMO_001216" },
  { name: "Sodium carbonate-Carbon dioxide buffer", gmo_id: "GMO_001503" },
  { name: "Sodium chlorate", gmo_id: "GMO_001722" },
  { name: "Sodium chloride", gmo_id: "GMO_001004" },
  { name: "Sodium chloride solution", gmo_id: "GMO_001355" },
  { name: "Sodium citrate", gmo_id: "GMO_001109" },
  { name: "Sodium citrate dihydrate", gmo_id: "GMO_001753" },
  { name: "Sodium citrate solution", gmo_id: "GMO_001321" },
  {
    name: "Sodium dihydrogen phosphate; Anhydrous monobasic sodium phosphate, Monosodium phosphate, Sodium phosphate monobasic anhydrous",
    gmo_id: "GMO_001352",
  },
  {
    name: "Sodium dihydrogen phosphate dihydrate; Anhydrous monobasic sodium phosphate dihydrate, Monosodium phosphate dihydrate",
    gmo_id: "GMO_001605",
  },
  {
    name: "Sodium dihydrogen phosphate monohydrate; Anhydrous monobasic sodium phosphate monohydrate, Monosodium phosphate monohydrate",
    gmo_id: "GMO_001606",
  },
  { name: "Sodium dithionite", gmo_id: "GMO_001354" },
  { name: "Sodium dithionite dihydrate", gmo_id: "GMO_001720" },
  { name: "Sodium dithionite solution", gmo_id: "GMO_001721" },
  { name: "Sodium fluoride", gmo_id: "GMO_001107" },
  {
    name: "Sodium formaldehyde sulfoxylate; Rongalite, Sodium hydroxymethylsulfinate, Sodium oxymethylene sulfoxylate",
    gmo_id: "GMO_001836",
  },
  { name: "Sodium formate", gmo_id: "GMO_001120" },
  { name: "Sodium formate solution", gmo_id: "GMO_001491" },
  { name: "Sodium fumarate solution", gmo_id: "GMO_001474" },
  { name: "Sodium gluconate", gmo_id: "GMO_001649" },
  { name: "Sodium glutamate; MSG, Monosodium glutamate", gmo_id: "GMO_001094" },
  { name: "Sodium glutamate monohydrate; Monosodium glutamate monohydrate", gmo_id: "GMO_001168" },
  { name: "Sodium glycerophosphate; Disodium beta-Glycerophosphate", gmo_id: "GMO_001405" },
  { name: "Sodium hydroxide", gmo_id: "GMO_001078" },
  { name: "Sodium hydroxide solution", gmo_id: "GMO_001300" },
  { name: "Sodium hygromycin solution", gmo_id: "GMO_001325" },
  { name: "Sodium lactate", gmo_id: "GMO_001090" },
  { name: "Sodium lactate solution", gmo_id: "GMO_001363" },
  { name: "Sodium malate", gmo_id: "GMO_001143" },
  { name: "Sodium metasilicate", gmo_id: "GMO_001341" },
  { name: "Sodium metasilicate nonahydrate", gmo_id: "GMO_001604" },
  { name: "Sodium metavanadate monohydrate", gmo_id: "GMO_001609" },
  { name: "Sodium molybdate", gmo_id: "GMO_001719" },
  { name: "Sodium molybdate dihydrate", gmo_id: "GMO_001011" },
  { name: "Sodium molybdate dihydrate solution", gmo_id: "GMO_001718" },
  { name: "Sodium molybdate solution", gmo_id: "GMO_001380" },
  { name: "Sodium n-hexanoate", gmo_id: "GMO_001256" },
  { name: "Sodium nitrate", gmo_id: "GMO_001049" },
  { name: "Sodium nitrate solution", gmo_id: "GMO_001472" },
  { name: "Sodium nitrite", gmo_id: "GMO_001329" },
  { name: "Sodium oleate", gmo_id: "GMO_001650" },
  { name: "Sodium palmitate", gmo_id: "GMO_001651" },
  { name: "Sodium phosphate buffer", gmo_id: "GMO_001124" },
  { name: "Sodium propionate", gmo_id: "GMO_001288" },
  { name: "Sodium pyruvate; Pyruvic acid sodium salt", gmo_id: "GMO_001055" },
  { name: "Sodium pyruvate solution; Pyruvic acid sodium salt solution", gmo_id: "GMO_001475" },
  { name: "Sodium resazurin solution", gmo_id: "GMO_001453" },
  { name: "Sodium selenate", gmo_id: "GMO_001602" },
  { name: "Sodium selenate pentahydrate", gmo_id: "GMO_001603" },
  { name: "Sodium selenate soution", gmo_id: "GMO_001477" },
  { name: "Sodium selenite", gmo_id: "GMO_001093" },
  { name: "Sodium selenite pentahydrate", gmo_id: "GMO_001046" },
  { name: "Sodium silicate", gmo_id: "GMO_001236" },
  { name: "Sodium silicate nonahydrate", gmo_id: "GMO_001198" },
  { name: "Sodium succinate", gmo_id: "GMO_001070" },
  { name: "Sodium succinate solution", gmo_id: "GMO_001462" },
  { name: "Sodium sulfate", gmo_id: "GMO_001052" },
  { name: "Sodium sulfide", gmo_id: "GMO_001323" },
  { name: "Sodium sulfide nonahydrate", gmo_id: "GMO_001014" },
  { name: "Sodium sulfide nonahydrate solution", gmo_id: "GMO_001494" },
  { name: "Sodium sulfide solution", gmo_id: "GMO_001315" },
  { name: "Sodium sulfite solution", gmo_id: "GMO_001452" },
  { name: "Sodium tartrate", gmo_id: "GMO_001200" },
  { name: "Sodium terephthalate", gmo_id: "GMO_001283" },
  { name: "Sodium tetrathionate", gmo_id: "GMO_001349" },
  { name: "Sodium thioglycolate; Sodium thioglycollate", gmo_id: "GMO_001132" },
  { name: "Sodium thiosulfate", gmo_id: "GMO_001098" },
  { name: "Sodium thiosulfate pentahydrate", gmo_id: "GMO_001041" },
  { name: "Sodium thiosulfate pentahydrate solution", gmo_id: "GMO_001486" },
  { name: "Sodium thiosulfate solution", gmo_id: "GMO_001471" },
  { name: "Sodium tungstate", gmo_id: "GMO_001086" },
  { name: "Sodium tungstate dihydrate", gmo_id: "GMO_001057" },
  { name: "Sodium tungstate monohydrate", gmo_id: "GMO_001186" },
  { name: "Soil extract", gmo_id: "GMO_001166" },
  { name: "Soluble starch", gmo_id: "GMO_001837" },
  { name: "Soluble starch (Difco)", gmo_id: "GMO_001653" },
  { name: "Soluble starch (Sigma)", gmo_id: "GMO_001654" },
  { name: "Sorbitan monooleate", gmo_id: "GMO_001207" },
  { name: "Sorbitol", gmo_id: "GMO_001369" },
  { name: "Soy protein isolate", gmo_id: "GMO_001346" },
  { name: "Soybean peptone; Soy peptone, Soya peptone", gmo_id: "GMO_001251" },
  { name: "Starch", gmo_id: "GMO_001054" },
  { name: "Starch from corn (SIGMA); Cornstarch", gmo_id: "GMO_001339" },
  { name: "Sterile horse serum", gmo_id: "GMO_001655" },
  { name: "Streptomycin sulfate", gmo_id: "GMO_001713" },
  { name: "Strontium chloride", gmo_id: "GMO_001153" },
  { name: "Strontium chloride hexahydrate", gmo_id: "GMO_001085" },
  { name: "Succinic acid", gmo_id: "GMO_001656" },
  { name: "Sucrose", gmo_id: "GMO_001067" },
  { name: "Sugar solution (JCM 537)", gmo_id: "GMO_001928" },
  { name: "Sulfur powder", gmo_id: "GMO_001062" },
  { name: "Sulfuric acid solution; Sulphuric acid", gmo_id: "GMO_001482" },
  { name: "TAPS", gmo_id: "GMO_001372" },
  {
    name: "TAPSO; N-[Tris(hydroxymethyl)methyl]-3-amino-2-hydroxypropanesulfonic acid",
    gmo_id: "GMO_001418",
  },
  { name: "TES", gmo_id: "GMO_001712" },
  { name: "Tap water", gmo_id: "GMO_001131" },
  { name: "Tetramethyl ammonium", gmo_id: "GMO_001659" },
  { name: "Thiamin solution", gmo_id: "GMO_001367" },
  { name: "Thiamine; Vitamin B1", gmo_id: "GMO_001230" },
  { name: "Thiamine hydrochloride", gmo_id: "GMO_001027" },
  { name: "Thiamine hydrochloride dihydrate", gmo_id: "GMO_001278" },
  { name: "Thiamine monophosphate", gmo_id: "GMO_001877" },
  { name: "Thiamine monophosphate chloride dihydrate", gmo_id: "GMO_001878" },
  { name: "Thiamine pyrophosphate; Cocarboxylase, TPP", gmo_id: "GMO_001660" },
  { name: "Thiamine pyrophosphate solution", gmo_id: "GMO_001457" },
  { name: "Thioglycolate medium", gmo_id: "GMO_001838" },
  { name: "Thioglycolate medium dehydrated", gmo_id: "GMO_001220" },
  { name: "Thioglycolate medium dehydrated (Wako)", gmo_id: "GMO_001227" },
  { name: "Thioglycolic acid; Mercaptoacetic acid", gmo_id: "GMO_001356" },
  { name: "Thioglycolic acid solution; Mercaptoacetic acid solution", gmo_id: "GMO_001319" },
  { name: "Thioglycollate medium (Sigma)", gmo_id: "GMO_001662" },
  { name: "Thiosulfate", gmo_id: "GMO_001927" },
  { name: "Threonine", gmo_id: "GMO_001802" },
  { name: "Thymidine", gmo_id: "GMO_001820" },
  { name: "Thymine", gmo_id: "GMO_001271" },
  { name: "Tin(II) chloride dihydrate", gmo_id: "GMO_001338" },
  { name: "Titanium(III) chloride; Titanium chloride", gmo_id: "GMO_001711" },
  { name: "Titanium(III) chloride solution", gmo_id: "GMO_001387" },
  { name: "Toluene", gmo_id: "GMO_001663" },
  { name: "Toluene solution", gmo_id: "GMO_001507" },
  { name: "Tomato", gmo_id: "GMO_001244" },
  { name: "Toray silicone SH 5535 solution", gmo_id: "GMO_001487" },
  { name: "Trace element solution (JCM 480)", gmo_id: "GMO_001913" },
  { name: "Trace metal element SL-10", gmo_id: "GMO_001855" },
  { name: "Trace metal element SL-6", gmo_id: "GMO_001852" },
  { name: "Trace metal element SL-7", gmo_id: "GMO_001853" },
  { name: "Trace metal element SL-8", gmo_id: "GMO_001854" },
  { name: "Trace mineral solution (JCM 151)", gmo_id: "GMO_001905" },
  { name: "Trace mineral solution (JCM 369)", gmo_id: "GMO_001906" },
  { name: "Trace mineral solution (JCM 411)", gmo_id: "GMO_001904" },
  { name: "Trehalose; Mycose, Tremalose", gmo_id: "GMO_001234" },
  { name: "Trichloroethylene", gmo_id: "GMO_001710" },
  { name: "Triethanolamine", gmo_id: "GMO_001664" },
  { name: "Trimethylamine hydrochloride", gmo_id: "GMO_001126" },
  { name: "Trimethylamine hydrochloride solution", gmo_id: "GMO_001739" },
  {
    name: "Tris; THAM, Tris base, Tris hydrochloride, Tris(hydroxymethyl)aminomethane",
    gmo_id: "GMO_001233",
  },
  { name: "Tris buffer; Tris hydrochloride buffer", gmo_id: "GMO_001730" },
  { name: "Trisodium EDTA", gmo_id: "GMO_001158" },
  { name: "Trisodium citrate", gmo_id: "GMO_001160" },
  { name: "Trisodium citrate dihydrate", gmo_id: "GMO_001249" },
  { name: "Trisodium citrate monohydrate", gmo_id: "GMO_001665" },
  { name: "Trypsin (Sigma-Aldrich)", gmo_id: "GMO_001666" },
  { name: "Trypticase", gmo_id: "GMO_001276" },
  { name: "Trypticase soy", gmo_id: "GMO_001408" },
  { name: "Trypticase soy agar (BBL)", gmo_id: "GMO_001669" },
  { name: "Trypto-soya agar (Nissui)", gmo_id: "GMO_001671" },
  { name: "Tryptophan", gmo_id: "GMO_001215" },
  { name: "Tungstic acid", gmo_id: "GMO_001560" },
  { name: "Turbo cornutus meat cut", gmo_id: "GMO_001269" },
  { name: "Tyrosine", gmo_id: "GMO_001807" },
  { name: "Ultrapure water", gmo_id: "GMO_001892" },
  { name: "Uracil", gmo_id: "GMO_001676" },
  { name: "Urea", gmo_id: "GMO_001133" },
  { name: "Uric acid", gmo_id: "GMO_001335" },
  { name: "Uridine-5-Triphosphate monosodium salt", gmo_id: "GMO_001866" },
  { name: "V-8 Juice", gmo_id: "GMO_001290" },
  { name: "Valeric acid; Pentanoic acid", gmo_id: "GMO_001181" },
  { name: "Valine", gmo_id: "GMO_001810" },
  { name: "Vanadyl sulfate", gmo_id: "GMO_001894" },
  { name: "Vanadyl sulfate dihydrate", gmo_id: "GMO_001332" },
  { name: "Vanadyl sulfate n-hydrate", gmo_id: "GMO_001151" },
  { name: "Vanadyl sulfate n-hydrate solution ", gmo_id: "GMO_001678" },
  { name: "Vanadyl sulfate pentahydrate", gmo_id: "GMO_001677" },
  { name: "Vancomycin hydrochloride solution", gmo_id: "GMO_001679" },
  { name: "Vegetable juice", gmo_id: "GMO_001400" },
  { name: "Vitamin K1", gmo_id: "GMO_001829" },
  { name: "Vitamin K1 solution", gmo_id: "GMO_001419" },
  { name: "Volvic water", gmo_id: "GMO_001441" },
  { name: "Water", gmo_id: "GMO_001891" },
  { name: "Whole egg", gmo_id: "GMO_001680" },
  { name: "Wine", gmo_id: "GMO_001416" },
  { name: "Wolfe's mineral solution", gmo_id: "GMO_001910" },
  { name: "Wolfe's mineral solution, modified (JCM 915)", gmo_id: "GMO_001911" },
  { name: "Xylan", gmo_id: "GMO_001401" },
  { name: "Xylose", gmo_id: "GMO_001239" },
  { name: "Yeast", gmo_id: "GMO_001898" },
  { name: "Yeast autolysate", gmo_id: "GMO_001683" },
  { name: "Yeast cell paste", gmo_id: "GMO_001914" },
  { name: "Yeast extract", gmo_id: "GMO_001003" },
  { name: "Yeast extract solution", gmo_id: "GMO_001292" },
  { name: "Yeast extract solution (Gibco 360-8180)", gmo_id: "GMO_001501" },
  { name: "Yeast nitrogen base (Difco)", gmo_id: "GMO_001686" },
  { name: "Zinc chloride", gmo_id: "GMO_001035" },
  { name: "Zinc chloride dihydrate", gmo_id: "GMO_001265" },
  { name: "Zinc sulfate", gmo_id: "GMO_001764" },
  { name: "Zinc sulfate dihydrate", gmo_id: "GMO_001688" },
  { name: "Zinc sulfate heptahydrate", gmo_id: "GMO_001023" },
  { name: "Zinc sulfate heptahydrate solution", gmo_id: "GMO_001360" },
  { name: "Zinc sulfate monohydrate", gmo_id: "GMO_001689" },
  { name: "Zinc sulfate solution", gmo_id: "GMO_001277" },
  { name: "alpha-Ketoglutaric acid", gmo_id: "GMO_001861" },
  { name: "alpha-Methylbutyric acid; 2-methylbutyric acid", gmo_id: "GMO_001299" },
  { name: "cis-4-Hydroxy-L-proline", gmo_id: "GMO_001781" },
  { name: "myo-Inositol", gmo_id: "GMO_001814" },
  { name: "n-Butanol; n-butyl alcohol, normal butanol", gmo_id: "GMO_001258" },
  { name: "trans-4-Hydroxy-L-proline", gmo_id: "GMO_001780" },
  { name: "Rabbit serum sterile non-hemolyzed (Pel-Freez, code No. 31125)", gmo_id: "GMO_001726" },
  {
    name: "Bacto yeast nitrogen base without amino acids and ammonium sulfate",
    gmo_id: "GMO_001382",
  },
  { name: "Gibco Horse Serum, heat inactivated, New Zealand origin", gmo_id: "GMO_001960" },
];
